FROM ocaml/opam:debian-9_ocaml-4.02.3

ENV CI=true
ENV TERM=dumb
ENV OCAML_VERSION="4.02.3"
ENV NPM_CONFIG_PREFIX="~/.npm-global"

RUN  curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN mkdir -p ~/.npm-global
RUN npm config set prefix $NPM_CONFIG_PREFIX
RUN npm install -g --unsafe-perm esy@0.1.27

COPY . /usr/src/app/
WORKDIR /usr/src/app/packages/kauri-components
RUN ~/.npm-global/bin/esy install

EXPOSE 6006
CMD "npm" "run" "test:chromatic"
