// flow-typed signature: e7ee9ae3bfff540934db3707c35976af
// flow-typed version: <<STUB>>/@pwa/next-workbox-webpack-plugin_v^0.4.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pwa/next-workbox-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pwa/next-workbox-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pwa/next-workbox-webpack-plugin/bin/next-workbox-start' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pwa/next-workbox-webpack-plugin/bin/next-workbox-start.js' {
  declare module.exports: $Exports<'@pwa/next-workbox-webpack-plugin/bin/next-workbox-start'>;
}
declare module '@pwa/next-workbox-webpack-plugin/index' {
  declare module.exports: $Exports<'@pwa/next-workbox-webpack-plugin'>;
}
declare module '@pwa/next-workbox-webpack-plugin/index.js' {
  declare module.exports: $Exports<'@pwa/next-workbox-webpack-plugin'>;
}
