// flow-typed signature: b5dde271f2edd4365b60de277df4b146
// flow-typed version: <<STUB>>/bs-css_v^7.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-css/example/bundle' {
  declare module.exports: any;
}

declare module 'bs-css/lib/js/example/example' {
  declare module.exports: any;
}

declare module 'bs-css/lib/js/example/test' {
  declare module.exports: any;
}

declare module 'bs-css/lib/js/src/Css' {
  declare module.exports: any;
}

declare module 'bs-css/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-css/example/bundle.js' {
  declare module.exports: $Exports<'bs-css/example/bundle'>;
}
declare module 'bs-css/lib/js/example/example.js' {
  declare module.exports: $Exports<'bs-css/lib/js/example/example'>;
}
declare module 'bs-css/lib/js/example/test.js' {
  declare module.exports: $Exports<'bs-css/lib/js/example/test'>;
}
declare module 'bs-css/lib/js/src/Css.js' {
  declare module.exports: $Exports<'bs-css/lib/js/src/Css'>;
}
declare module 'bs-css/webpack.config.js' {
  declare module.exports: $Exports<'bs-css/webpack.config'>;
}
