// flow-typed signature: f0590317ae207d7759868103e8e6dfb0
// flow-typed version: <<STUB>>/bs-enzyme_v^0.4.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-enzyme' {
  declare module.exports: any;
}
