// flow-typed signature: 187298b954adeb18c5c21342cf086607
// flow-typed version: <<STUB>>/bs-moment_v^0.3.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-moment/lib/js/src/MomentRe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-moment/lib/js/src/MomentRe.js' {
  declare module.exports: $Exports<'bs-moment/lib/js/src/MomentRe'>;
}
