// flow-typed signature: ab5c497562b87d4f99b722bbc64df07c
// flow-typed version: <<STUB>>/bs-webapi_v^0.11.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-webapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-webapi' {
  declare module.exports: any;
}
