// flow-typed signature: 67a2d8ac7049d37f175319f12d5020e1
// flow-typed version: <<STUB>>/dependency-env_v^0.1.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-env' {
  declare module.exports: any;
}
