// flow-typed signature: 0bd99bd2dce54913f30391472ec4703b
// flow-typed version: <<STUB>>/driver.js_v^0.5.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'driver.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'driver.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'driver.js/demo/scripts/demo' {
  declare module.exports: any;
}

declare module 'driver.js/demo/scripts/emoji' {
  declare module.exports: any;
}

declare module 'driver.js/dist/driver.min' {
  declare module.exports: any;
}

declare module 'driver.js/server' {
  declare module.exports: any;
}

declare module 'driver.js/src/common/constants' {
  declare module.exports: any;
}

declare module 'driver.js/src/common/polyfill' {
  declare module.exports: any;
}

declare module 'driver.js/src/common/utils' {
  declare module.exports: any;
}

declare module 'driver.js/src/core/element' {
  declare module.exports: any;
}

declare module 'driver.js/src/core/overlay' {
  declare module.exports: any;
}

declare module 'driver.js/src/core/popover' {
  declare module.exports: any;
}

declare module 'driver.js/src/core/position' {
  declare module.exports: any;
}

declare module 'driver.js/src/core/stage' {
  declare module.exports: any;
}

declare module 'driver.js/src/index' {
  declare module.exports: any;
}

declare module 'driver.js/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'driver.js/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'driver.js/demo/scripts/demo.js' {
  declare module.exports: $Exports<'driver.js/demo/scripts/demo'>;
}
declare module 'driver.js/demo/scripts/emoji.js' {
  declare module.exports: $Exports<'driver.js/demo/scripts/emoji'>;
}
declare module 'driver.js/dist/driver.min.js' {
  declare module.exports: $Exports<'driver.js/dist/driver.min'>;
}
declare module 'driver.js/server.js' {
  declare module.exports: $Exports<'driver.js/server'>;
}
declare module 'driver.js/src/common/constants.js' {
  declare module.exports: $Exports<'driver.js/src/common/constants'>;
}
declare module 'driver.js/src/common/polyfill.js' {
  declare module.exports: $Exports<'driver.js/src/common/polyfill'>;
}
declare module 'driver.js/src/common/utils.js' {
  declare module.exports: $Exports<'driver.js/src/common/utils'>;
}
declare module 'driver.js/src/core/element.js' {
  declare module.exports: $Exports<'driver.js/src/core/element'>;
}
declare module 'driver.js/src/core/overlay.js' {
  declare module.exports: $Exports<'driver.js/src/core/overlay'>;
}
declare module 'driver.js/src/core/popover.js' {
  declare module.exports: $Exports<'driver.js/src/core/popover'>;
}
declare module 'driver.js/src/core/position.js' {
  declare module.exports: $Exports<'driver.js/src/core/position'>;
}
declare module 'driver.js/src/core/stage.js' {
  declare module.exports: $Exports<'driver.js/src/core/stage'>;
}
declare module 'driver.js/src/index.js' {
  declare module.exports: $Exports<'driver.js/src/index'>;
}
declare module 'driver.js/webpack.config.demo.js' {
  declare module.exports: $Exports<'driver.js/webpack.config.demo'>;
}
declare module 'driver.js/webpack.config.prod.js' {
  declare module.exports: $Exports<'driver.js/webpack.config.prod'>;
}
