// flow-typed signature: 1f02de979f3ec6441179acb3de8e9f44
// flow-typed version: <<STUB>>/gramophone_v^0.0.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gramophone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gramophone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gramophone/misc/substack' {
  declare module.exports: any;
}

declare module 'gramophone/misc/test' {
  declare module.exports: any;
}

declare module 'gramophone/test/extract' {
  declare module.exports: any;
}

declare module 'gramophone/test/stream' {
  declare module.exports: any;
}

declare module 'gramophone/test/transform-stream' {
  declare module.exports: any;
}

declare module 'gramophone/tfidf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gramophone/index' {
  declare module.exports: $Exports<'gramophone'>;
}
declare module 'gramophone/index.js' {
  declare module.exports: $Exports<'gramophone'>;
}
declare module 'gramophone/misc/substack.js' {
  declare module.exports: $Exports<'gramophone/misc/substack'>;
}
declare module 'gramophone/misc/test.js' {
  declare module.exports: $Exports<'gramophone/misc/test'>;
}
declare module 'gramophone/test/extract.js' {
  declare module.exports: $Exports<'gramophone/test/extract'>;
}
declare module 'gramophone/test/stream.js' {
  declare module.exports: $Exports<'gramophone/test/stream'>;
}
declare module 'gramophone/test/transform-stream.js' {
  declare module.exports: $Exports<'gramophone/test/transform-stream'>;
}
declare module 'gramophone/tfidf.js' {
  declare module.exports: $Exports<'gramophone/tfidf'>;
}
