// flow-typed signature: e11b60ccfd4821381767478441ed5ec3
// flow-typed version: <<STUB>>/graphql_ppx_v^0.2.7/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql_ppx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql_ppx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql_ppx/copyPlatformBinaryInPlace' {
  declare module.exports: any;
}

declare module 'graphql_ppx/sendIntrospectionQuery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql_ppx/copyPlatformBinaryInPlace.js' {
  declare module.exports: $Exports<'graphql_ppx/copyPlatformBinaryInPlace'>;
}
declare module 'graphql_ppx/sendIntrospectionQuery.js' {
  declare module.exports: $Exports<'graphql_ppx/sendIntrospectionQuery'>;
}
