// flow-typed signature: 4ddd96046c691e72c2f6d860ec006525
// flow-typed version: <<STUB>>/highlightjs_v^9.10.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highlightjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'highlightjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highlightjs/highlight.pack' {
  declare module.exports: any;
}

declare module 'highlightjs/highlight.pack.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highlightjs/highlight.pack.js' {
  declare module.exports: $Exports<'highlightjs/highlight.pack'>;
}
declare module 'highlightjs/highlight.pack.min.js' {
  declare module.exports: $Exports<'highlightjs/highlight.pack.min'>;
}
