// flow-typed signature: 02cd604d64cf6f15c6da90e73592e5e4
// flow-typed version: <<STUB>>/mezr_v^0.6.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mezr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mezr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mezr/gulpfile' {
  declare module.exports: any;
}

declare module 'mezr/karma.conf' {
  declare module.exports: any;
}

declare module 'mezr/mezr' {
  declare module.exports: any;
}

declare module 'mezr/mezr.min' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/containing-block' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/dimensions' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/distance' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/intersection' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/offset' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/overflow' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/place' {
  declare module.exports: any;
}

declare module 'mezr/tests/modules/rect' {
  declare module.exports: any;
}

declare module 'mezr/tests/run-tests' {
  declare module.exports: any;
}

declare module 'mezr/tests/testsuite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mezr/gulpfile.js' {
  declare module.exports: $Exports<'mezr/gulpfile'>;
}
declare module 'mezr/karma.conf.js' {
  declare module.exports: $Exports<'mezr/karma.conf'>;
}
declare module 'mezr/mezr.js' {
  declare module.exports: $Exports<'mezr/mezr'>;
}
declare module 'mezr/mezr.min.js' {
  declare module.exports: $Exports<'mezr/mezr.min'>;
}
declare module 'mezr/tests/modules/containing-block.js' {
  declare module.exports: $Exports<'mezr/tests/modules/containing-block'>;
}
declare module 'mezr/tests/modules/dimensions.js' {
  declare module.exports: $Exports<'mezr/tests/modules/dimensions'>;
}
declare module 'mezr/tests/modules/distance.js' {
  declare module.exports: $Exports<'mezr/tests/modules/distance'>;
}
declare module 'mezr/tests/modules/intersection.js' {
  declare module.exports: $Exports<'mezr/tests/modules/intersection'>;
}
declare module 'mezr/tests/modules/offset.js' {
  declare module.exports: $Exports<'mezr/tests/modules/offset'>;
}
declare module 'mezr/tests/modules/overflow.js' {
  declare module.exports: $Exports<'mezr/tests/modules/overflow'>;
}
declare module 'mezr/tests/modules/place.js' {
  declare module.exports: $Exports<'mezr/tests/modules/place'>;
}
declare module 'mezr/tests/modules/rect.js' {
  declare module.exports: $Exports<'mezr/tests/modules/rect'>;
}
declare module 'mezr/tests/run-tests.js' {
  declare module.exports: $Exports<'mezr/tests/run-tests'>;
}
declare module 'mezr/tests/testsuite.js' {
  declare module.exports: $Exports<'mezr/tests/testsuite'>;
}
