// flow-typed signature: d3253de1c3d5cbbba722b77593882847
// flow-typed version: <<STUB>>/rake-js_v^0.1.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rake-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rake-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rake-js/dist/lib/data_structures/phrase' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/data_structures/string_counter' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/data_structures/string_dictionary' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/data_structures/word_matrix' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/index' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/rake' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/dutch' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/english' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/german' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/italian' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/portugese' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/spanish' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/stopwords/swedish' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/guess_language' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/parser' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/preprocessor' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/stemmer' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/stoplist' {
  declare module.exports: any;
}

declare module 'rake-js/dist/lib/tools/strip' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/data_structures/string_counter' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/data_structures/string_dictionary' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/rake' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/tools/guess_language' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/tools/preprocessor' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/tools/stemmer' {
  declare module.exports: any;
}

declare module 'rake-js/dist/test/tools/strip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rake-js/dist/lib/data_structures/phrase.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/data_structures/phrase'>;
}
declare module 'rake-js/dist/lib/data_structures/string_counter.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/data_structures/string_counter'>;
}
declare module 'rake-js/dist/lib/data_structures/string_dictionary.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/data_structures/string_dictionary'>;
}
declare module 'rake-js/dist/lib/data_structures/word_matrix.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/data_structures/word_matrix'>;
}
declare module 'rake-js/dist/lib/index.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/index'>;
}
declare module 'rake-js/dist/lib/rake.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/rake'>;
}
declare module 'rake-js/dist/lib/stopwords/dutch.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/dutch'>;
}
declare module 'rake-js/dist/lib/stopwords/english.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/english'>;
}
declare module 'rake-js/dist/lib/stopwords/german.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/german'>;
}
declare module 'rake-js/dist/lib/stopwords/italian.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/italian'>;
}
declare module 'rake-js/dist/lib/stopwords/portugese.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/portugese'>;
}
declare module 'rake-js/dist/lib/stopwords/spanish.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/spanish'>;
}
declare module 'rake-js/dist/lib/stopwords/swedish.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/stopwords/swedish'>;
}
declare module 'rake-js/dist/lib/tools/guess_language.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/guess_language'>;
}
declare module 'rake-js/dist/lib/tools/parser.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/parser'>;
}
declare module 'rake-js/dist/lib/tools/preprocessor.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/preprocessor'>;
}
declare module 'rake-js/dist/lib/tools/stemmer.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/stemmer'>;
}
declare module 'rake-js/dist/lib/tools/stoplist.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/stoplist'>;
}
declare module 'rake-js/dist/lib/tools/strip.js' {
  declare module.exports: $Exports<'rake-js/dist/lib/tools/strip'>;
}
declare module 'rake-js/dist/test/data_structures/string_counter.js' {
  declare module.exports: $Exports<'rake-js/dist/test/data_structures/string_counter'>;
}
declare module 'rake-js/dist/test/data_structures/string_dictionary.js' {
  declare module.exports: $Exports<'rake-js/dist/test/data_structures/string_dictionary'>;
}
declare module 'rake-js/dist/test/rake.js' {
  declare module.exports: $Exports<'rake-js/dist/test/rake'>;
}
declare module 'rake-js/dist/test/tools/guess_language.js' {
  declare module.exports: $Exports<'rake-js/dist/test/tools/guess_language'>;
}
declare module 'rake-js/dist/test/tools/preprocessor.js' {
  declare module.exports: $Exports<'rake-js/dist/test/tools/preprocessor'>;
}
declare module 'rake-js/dist/test/tools/stemmer.js' {
  declare module.exports: $Exports<'rake-js/dist/test/tools/stemmer'>;
}
declare module 'rake-js/dist/test/tools/strip.js' {
  declare module.exports: $Exports<'rake-js/dist/test/tools/strip'>;
}
