// flow-typed signature: c1516fb62b1508060606f8a1b86d4d0d
// flow-typed version: <<STUB>>/react-youtube_v^7.5.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-youtube'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-youtube' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-youtube/build/preset-es2015' {
  declare module.exports: any;
}

declare module 'react-youtube/dist/YouTube' {
  declare module.exports: any;
}

declare module 'react-youtube/es/YouTube' {
  declare module.exports: any;
}

declare module 'react-youtube/test/helpers/fullRender' {
  declare module.exports: any;
}

declare module 'react-youtube/test/helpers/setupEnvironment' {
  declare module.exports: any;
}

declare module 'react-youtube/test/helpers/setupYouTube' {
  declare module.exports: any;
}

declare module 'react-youtube/test/helpers/shallowRender' {
  declare module.exports: any;
}

declare module 'react-youtube/test/YouTube-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-youtube/build/preset-es2015.js' {
  declare module.exports: $Exports<'react-youtube/build/preset-es2015'>;
}
declare module 'react-youtube/dist/YouTube.js' {
  declare module.exports: $Exports<'react-youtube/dist/YouTube'>;
}
declare module 'react-youtube/es/YouTube.js' {
  declare module.exports: $Exports<'react-youtube/es/YouTube'>;
}
declare module 'react-youtube/test/helpers/fullRender.js' {
  declare module.exports: $Exports<'react-youtube/test/helpers/fullRender'>;
}
declare module 'react-youtube/test/helpers/setupEnvironment.js' {
  declare module.exports: $Exports<'react-youtube/test/helpers/setupEnvironment'>;
}
declare module 'react-youtube/test/helpers/setupYouTube.js' {
  declare module.exports: $Exports<'react-youtube/test/helpers/setupYouTube'>;
}
declare module 'react-youtube/test/helpers/shallowRender.js' {
  declare module.exports: $Exports<'react-youtube/test/helpers/shallowRender'>;
}
declare module 'react-youtube/test/YouTube-test.js' {
  declare module.exports: $Exports<'react-youtube/test/YouTube-test'>;
}
