// flow-typed signature: d008ef5996e758412bf1a7cb0d20d385
// flow-typed version: <<STUB>>/react-fast-highlight_v^2.2.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fast-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fast-highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fast-highlight/lib/__tests__/BareHighlight' {
  declare module.exports: any;
}

declare module 'react-fast-highlight/lib/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-fast-highlight/lib/BareHighlight' {
  declare module.exports: any;
}

declare module 'react-fast-highlight/lib/Highlight' {
  declare module.exports: any;
}

declare module 'react-fast-highlight/lib/index' {
  declare module.exports: any;
}

declare module 'react-fast-highlight/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fast-highlight/lib/__tests__/BareHighlight.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/__tests__/BareHighlight'>;
}
declare module 'react-fast-highlight/lib/__tests__/index.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/__tests__/index'>;
}
declare module 'react-fast-highlight/lib/BareHighlight.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/BareHighlight'>;
}
declare module 'react-fast-highlight/lib/Highlight.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/Highlight'>;
}
declare module 'react-fast-highlight/lib/index.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/index'>;
}
declare module 'react-fast-highlight/lib/worker.js' {
  declare module.exports: $Exports<'react-fast-highlight/lib/worker'>;
}
