// flow-typed signature: 8a21ec8d98b93eee5929b6cf1810e651
// flow-typed version: <<STUB>>/reason-apollo_v^0.9.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reason-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reason-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reason-apollo/src/ApolloClient.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ApolloConsumer.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ApolloInMemoryCache.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ApolloLinks.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ApolloProvider.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/graphql-types/ReasonApolloMutation.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/graphql-types/ReasonApolloQuery.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ReasonApollo.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ReasonApolloTypes.bs' {
  declare module.exports: any;
}

declare module 'reason-apollo/src/ReasonApolloUtils.bs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reason-apollo/src/ApolloClient.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ApolloClient.bs'>;
}
declare module 'reason-apollo/src/ApolloConsumer.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ApolloConsumer.bs'>;
}
declare module 'reason-apollo/src/ApolloInMemoryCache.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ApolloInMemoryCache.bs'>;
}
declare module 'reason-apollo/src/ApolloLinks.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ApolloLinks.bs'>;
}
declare module 'reason-apollo/src/ApolloProvider.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ApolloProvider.bs'>;
}
declare module 'reason-apollo/src/graphql-types/ReasonApolloMutation.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/graphql-types/ReasonApolloMutation.bs'>;
}
declare module 'reason-apollo/src/graphql-types/ReasonApolloQuery.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/graphql-types/ReasonApolloQuery.bs'>;
}
declare module 'reason-apollo/src/ReasonApollo.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ReasonApollo.bs'>;
}
declare module 'reason-apollo/src/ReasonApolloTypes.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ReasonApolloTypes.bs'>;
}
declare module 'reason-apollo/src/ReasonApolloUtils.bs.js' {
  declare module.exports: $Exports<'reason-apollo/src/ReasonApolloUtils.bs'>;
}
