// flow-typed signature: 14f199803fcf4d1a90d292f288f193b0
// flow-typed version: <<STUB>>/redraft_v^0.10.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redraft'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redraft' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redraft/__mocks__/react' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/cleanup' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/createBlockRenderer.test' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/decorators' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/flat' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/render' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/renderWithReact' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/unicode' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/utils/helpers' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/utils/raws' {
  declare module.exports: any;
}

declare module 'redraft/__tests__/utils/TestDecorator' {
  declare module.exports: any;
}

declare module 'redraft/benchmarks/emoji' {
  declare module.exports: any;
}

declare module 'redraft/lib/ContentNode' {
  declare module.exports: any;
}

declare module 'redraft/lib/createBlockRenderer' {
  declare module.exports: any;
}

declare module 'redraft/lib/createStyleRenderer' {
  declare module.exports: any;
}

declare module 'redraft/lib/defaultOptions' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/arrayEqual' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/checkCleanup' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/checkJoin' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/CompositeDecorator' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/getKeyGenerator' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/MultiDecorator' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/pushString' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/stubContentBlock' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/warn' {
  declare module.exports: any;
}

declare module 'redraft/lib/index' {
  declare module.exports: any;
}

declare module 'redraft/lib/RawParser' {
  declare module.exports: any;
}

declare module 'redraft/lib/render' {
  declare module.exports: any;
}

declare module 'redraft/lib/withDecorators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redraft/__mocks__/react.js' {
  declare module.exports: $Exports<'redraft/__mocks__/react'>;
}
declare module 'redraft/__tests__/cleanup.js' {
  declare module.exports: $Exports<'redraft/__tests__/cleanup'>;
}
declare module 'redraft/__tests__/createBlockRenderer.test.js' {
  declare module.exports: $Exports<'redraft/__tests__/createBlockRenderer.test'>;
}
declare module 'redraft/__tests__/decorators.js' {
  declare module.exports: $Exports<'redraft/__tests__/decorators'>;
}
declare module 'redraft/__tests__/flat.js' {
  declare module.exports: $Exports<'redraft/__tests__/flat'>;
}
declare module 'redraft/__tests__/render.js' {
  declare module.exports: $Exports<'redraft/__tests__/render'>;
}
declare module 'redraft/__tests__/renderWithReact.js' {
  declare module.exports: $Exports<'redraft/__tests__/renderWithReact'>;
}
declare module 'redraft/__tests__/unicode.js' {
  declare module.exports: $Exports<'redraft/__tests__/unicode'>;
}
declare module 'redraft/__tests__/utils/helpers.js' {
  declare module.exports: $Exports<'redraft/__tests__/utils/helpers'>;
}
declare module 'redraft/__tests__/utils/raws.js' {
  declare module.exports: $Exports<'redraft/__tests__/utils/raws'>;
}
declare module 'redraft/__tests__/utils/TestDecorator.js' {
  declare module.exports: $Exports<'redraft/__tests__/utils/TestDecorator'>;
}
declare module 'redraft/benchmarks/emoji.js' {
  declare module.exports: $Exports<'redraft/benchmarks/emoji'>;
}
declare module 'redraft/lib/ContentNode.js' {
  declare module.exports: $Exports<'redraft/lib/ContentNode'>;
}
declare module 'redraft/lib/createBlockRenderer.js' {
  declare module.exports: $Exports<'redraft/lib/createBlockRenderer'>;
}
declare module 'redraft/lib/createStyleRenderer.js' {
  declare module.exports: $Exports<'redraft/lib/createStyleRenderer'>;
}
declare module 'redraft/lib/defaultOptions.js' {
  declare module.exports: $Exports<'redraft/lib/defaultOptions'>;
}
declare module 'redraft/lib/helpers/arrayEqual.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/arrayEqual'>;
}
declare module 'redraft/lib/helpers/checkCleanup.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/checkCleanup'>;
}
declare module 'redraft/lib/helpers/checkJoin.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/checkJoin'>;
}
declare module 'redraft/lib/helpers/CompositeDecorator.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/CompositeDecorator'>;
}
declare module 'redraft/lib/helpers/getKeyGenerator.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/getKeyGenerator'>;
}
declare module 'redraft/lib/helpers/MultiDecorator.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/MultiDecorator'>;
}
declare module 'redraft/lib/helpers/pushString.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/pushString'>;
}
declare module 'redraft/lib/helpers/stubContentBlock.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/stubContentBlock'>;
}
declare module 'redraft/lib/helpers/warn.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/warn'>;
}
declare module 'redraft/lib/index.js' {
  declare module.exports: $Exports<'redraft/lib/index'>;
}
declare module 'redraft/lib/RawParser.js' {
  declare module.exports: $Exports<'redraft/lib/RawParser'>;
}
declare module 'redraft/lib/render.js' {
  declare module.exports: $Exports<'redraft/lib/render'>;
}
declare module 'redraft/lib/withDecorators.js' {
  declare module.exports: $Exports<'redraft/lib/withDecorators'>;
}
