// flow-typed signature: 231f09f61b3d38b02339dda5aea5793c
// flow-typed version: <<STUB>>/showdown-xss-filter_v^0.2.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'showdown-xss-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'showdown-xss-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'showdown-xss-filter/showdown-xss-filter' {
  declare module.exports: any;
}

declare module 'showdown-xss-filter/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'showdown-xss-filter/showdown-xss-filter.js' {
  declare module.exports: $Exports<'showdown-xss-filter/showdown-xss-filter'>;
}
declare module 'showdown-xss-filter/test/test.js' {
  declare module.exports: $Exports<'showdown-xss-filter/test/test'>;
}
