// flow-typed signature: 953ca044eb3e62559e141851ecbb88d1
// flow-typed version: <<STUB>>/trianglify_v^1.2.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trianglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trianglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trianglify/dist/trianglify.min' {
  declare module.exports: any;
}

declare module 'trianglify/examples/save-as-png' {
  declare module.exports: any;
}

declare module 'trianglify/gulpfile' {
  declare module.exports: any;
}

declare module 'trianglify/lib/colorbrewer' {
  declare module.exports: any;
}

declare module 'trianglify/lib/pattern' {
  declare module.exports: any;
}

declare module 'trianglify/lib/points' {
  declare module.exports: any;
}

declare module 'trianglify/lib/trianglify' {
  declare module.exports: any;
}

declare module 'trianglify/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'trianglify/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trianglify/dist/trianglify.min.js' {
  declare module.exports: $Exports<'trianglify/dist/trianglify.min'>;
}
declare module 'trianglify/examples/save-as-png.js' {
  declare module.exports: $Exports<'trianglify/examples/save-as-png'>;
}
declare module 'trianglify/gulpfile.js' {
  declare module.exports: $Exports<'trianglify/gulpfile'>;
}
declare module 'trianglify/lib/colorbrewer.js' {
  declare module.exports: $Exports<'trianglify/lib/colorbrewer'>;
}
declare module 'trianglify/lib/pattern.js' {
  declare module.exports: $Exports<'trianglify/lib/pattern'>;
}
declare module 'trianglify/lib/points.js' {
  declare module.exports: $Exports<'trianglify/lib/points'>;
}
declare module 'trianglify/lib/trianglify.js' {
  declare module.exports: $Exports<'trianglify/lib/trianglify'>;
}
declare module 'trianglify/scripts/postinstall.js' {
  declare module.exports: $Exports<'trianglify/scripts/postinstall'>;
}
declare module 'trianglify/test/test.js' {
  declare module.exports: $Exports<'trianglify/test/test'>;
}
