// flow-typed signature: 0ab7c02677472a21c322778eda9e00b7
// flow-typed version: <<STUB>>/truffle-hdwallet-provider_v^0.0.5/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-hdwallet-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-hdwallet-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-hdwallet-provider/test/provider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-hdwallet-provider/index' {
  declare module.exports: $Exports<'truffle-hdwallet-provider'>;
}
declare module 'truffle-hdwallet-provider/index.js' {
  declare module.exports: $Exports<'truffle-hdwallet-provider'>;
}
declare module 'truffle-hdwallet-provider/test/provider.js' {
  declare module.exports: $Exports<'truffle-hdwallet-provider/test/provider'>;
}
