// flow-typed signature: ec81db47f425d86e3f82bcac8245f5e2
// flow-typed version: <<STUB>>/typescript-styled-plugin_v^0.2.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript-styled-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript-styled-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript-styled-plugin/lib/config' {
  declare module.exports: any;
}

declare module 'typescript-styled-plugin/lib/configuration' {
  declare module.exports: any;
}

declare module 'typescript-styled-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'typescript-styled-plugin/lib/styled-template-language-service' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript-styled-plugin/lib/config.js' {
  declare module.exports: $Exports<'typescript-styled-plugin/lib/config'>;
}
declare module 'typescript-styled-plugin/lib/configuration.js' {
  declare module.exports: $Exports<'typescript-styled-plugin/lib/configuration'>;
}
declare module 'typescript-styled-plugin/lib/index.js' {
  declare module.exports: $Exports<'typescript-styled-plugin/lib/index'>;
}
declare module 'typescript-styled-plugin/lib/styled-template-language-service.js' {
  declare module.exports: $Exports<'typescript-styled-plugin/lib/styled-template-language-service'>;
}
