// flow-typed signature: fdf1a35c33f88d8dd1f898ff55922570
// flow-typed version: <<STUB>>/vrroom_vglennsl/vrroom/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vrroom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vrroom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vrroom/examples/classNames.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/ControlIf.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/ControlIfSome.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/ControlMap.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/ControlMapList.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/Fragment.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/index.bs' {
  declare module.exports: any;
}

declare module 'vrroom/examples/pure.bs' {
  declare module.exports: any;
}

declare module 'vrroom/src/Vrroom.bs' {
  declare module.exports: any;
}

declare module 'vrroom/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vrroom/examples/classNames.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/classNames.bs'>;
}
declare module 'vrroom/examples/ControlIf.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/ControlIf.bs'>;
}
declare module 'vrroom/examples/ControlIfSome.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/ControlIfSome.bs'>;
}
declare module 'vrroom/examples/ControlMap.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/ControlMap.bs'>;
}
declare module 'vrroom/examples/ControlMapList.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/ControlMapList.bs'>;
}
declare module 'vrroom/examples/Fragment.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/Fragment.bs'>;
}
declare module 'vrroom/examples/index.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/index.bs'>;
}
declare module 'vrroom/examples/pure.bs.js' {
  declare module.exports: $Exports<'vrroom/examples/pure.bs'>;
}
declare module 'vrroom/src/Vrroom.bs.js' {
  declare module.exports: $Exports<'vrroom/src/Vrroom.bs'>;
}
declare module 'vrroom/webpack.config.js' {
  declare module.exports: $Exports<'vrroom/webpack.config'>;
}
