// flow-typed signature: fccc96b4242d0e69d17c4a3e9f13f7a7
// flow-typed version: <<STUB>>/web3-provider-engine_v8.4.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-provider-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-provider-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-provider-engine/dist/ProviderEngine' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/dist/ZeroClientProvider' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/example' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/cache' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/default-fixture' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/etherscan' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/filters' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/fixture' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/gasprice' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/hooked-wallet-ethtx' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/hooked-wallet' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/ipc' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/nonce-tracker' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/rpc' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/sanitizer' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/solc' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/subprovider' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/vm' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/wallet' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/web3' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/subproviders/whitelist' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/basic' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/cache' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/filters' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/index' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/nonce' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/solc' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/subproviders/cache' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/subproviders/etherscan' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/subproviders/index' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/subproviders/ipc' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/subproviders/sanitizer' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/util/block' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/util/inject-metrics' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/util/mock-subprovider' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/util/passthrough' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/test/wallet' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/async' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/create-payload' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/estimate-gas' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/random-id' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/rpc-cache-utils' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/util/stoplight' {
  declare module.exports: any;
}

declare module 'web3-provider-engine/zero' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-provider-engine/dist/ProviderEngine.js' {
  declare module.exports: $Exports<'web3-provider-engine/dist/ProviderEngine'>;
}
declare module 'web3-provider-engine/dist/ZeroClientProvider.js' {
  declare module.exports: $Exports<'web3-provider-engine/dist/ZeroClientProvider'>;
}
declare module 'web3-provider-engine/example.js' {
  declare module.exports: $Exports<'web3-provider-engine/example'>;
}
declare module 'web3-provider-engine/index' {
  declare module.exports: $Exports<'web3-provider-engine'>;
}
declare module 'web3-provider-engine/index.js' {
  declare module.exports: $Exports<'web3-provider-engine'>;
}
declare module 'web3-provider-engine/subproviders/cache.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/cache'>;
}
declare module 'web3-provider-engine/subproviders/default-fixture.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/default-fixture'>;
}
declare module 'web3-provider-engine/subproviders/etherscan.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/etherscan'>;
}
declare module 'web3-provider-engine/subproviders/filters.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/filters'>;
}
declare module 'web3-provider-engine/subproviders/fixture.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/fixture'>;
}
declare module 'web3-provider-engine/subproviders/gasprice.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/gasprice'>;
}
declare module 'web3-provider-engine/subproviders/hooked-wallet-ethtx.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/hooked-wallet-ethtx'>;
}
declare module 'web3-provider-engine/subproviders/hooked-wallet.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/hooked-wallet'>;
}
declare module 'web3-provider-engine/subproviders/ipc.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/ipc'>;
}
declare module 'web3-provider-engine/subproviders/nonce-tracker.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/nonce-tracker'>;
}
declare module 'web3-provider-engine/subproviders/rpc.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/rpc'>;
}
declare module 'web3-provider-engine/subproviders/sanitizer.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/sanitizer'>;
}
declare module 'web3-provider-engine/subproviders/solc.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/solc'>;
}
declare module 'web3-provider-engine/subproviders/subprovider.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/subprovider'>;
}
declare module 'web3-provider-engine/subproviders/vm.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/vm'>;
}
declare module 'web3-provider-engine/subproviders/wallet.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/wallet'>;
}
declare module 'web3-provider-engine/subproviders/web3.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/web3'>;
}
declare module 'web3-provider-engine/subproviders/whitelist.js' {
  declare module.exports: $Exports<'web3-provider-engine/subproviders/whitelist'>;
}
declare module 'web3-provider-engine/test/basic.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/basic'>;
}
declare module 'web3-provider-engine/test/cache.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/cache'>;
}
declare module 'web3-provider-engine/test/filters.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/filters'>;
}
declare module 'web3-provider-engine/test/index.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/index'>;
}
declare module 'web3-provider-engine/test/nonce.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/nonce'>;
}
declare module 'web3-provider-engine/test/solc.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/solc'>;
}
declare module 'web3-provider-engine/test/subproviders/cache.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/subproviders/cache'>;
}
declare module 'web3-provider-engine/test/subproviders/etherscan.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/subproviders/etherscan'>;
}
declare module 'web3-provider-engine/test/subproviders/index.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/subproviders/index'>;
}
declare module 'web3-provider-engine/test/subproviders/ipc.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/subproviders/ipc'>;
}
declare module 'web3-provider-engine/test/subproviders/sanitizer.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/subproviders/sanitizer'>;
}
declare module 'web3-provider-engine/test/util/block.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/util/block'>;
}
declare module 'web3-provider-engine/test/util/inject-metrics.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/util/inject-metrics'>;
}
declare module 'web3-provider-engine/test/util/mock-subprovider.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/util/mock-subprovider'>;
}
declare module 'web3-provider-engine/test/util/passthrough.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/util/passthrough'>;
}
declare module 'web3-provider-engine/test/wallet.js' {
  declare module.exports: $Exports<'web3-provider-engine/test/wallet'>;
}
declare module 'web3-provider-engine/util/async.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/async'>;
}
declare module 'web3-provider-engine/util/create-payload.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/create-payload'>;
}
declare module 'web3-provider-engine/util/estimate-gas.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/estimate-gas'>;
}
declare module 'web3-provider-engine/util/random-id.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/random-id'>;
}
declare module 'web3-provider-engine/util/rpc-cache-utils.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/rpc-cache-utils'>;
}
declare module 'web3-provider-engine/util/stoplight.js' {
  declare module.exports: $Exports<'web3-provider-engine/util/stoplight'>;
}
declare module 'web3-provider-engine/zero.js' {
  declare module.exports: $Exports<'web3-provider-engine/zero'>;
}
