// flow-typed signature: 86c8322327ad2f989336617ac81619d2
// flow-typed version: <<STUB>>/webpack-jarvis_v^0.2.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-jarvis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-jarvis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-jarvis/bin/client/bundle' {
  declare module.exports: any;
}

declare module 'webpack-jarvis/bin/plugin/index' {
  declare module.exports: any;
}

declare module 'webpack-jarvis/bin/plugin/reporter-util' {
  declare module.exports: any;
}

declare module 'webpack-jarvis/bin/plugin/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-jarvis/bin/client/bundle.js' {
  declare module.exports: $Exports<'webpack-jarvis/bin/client/bundle'>;
}
declare module 'webpack-jarvis/bin/plugin/index.js' {
  declare module.exports: $Exports<'webpack-jarvis/bin/plugin/index'>;
}
declare module 'webpack-jarvis/bin/plugin/reporter-util.js' {
  declare module.exports: $Exports<'webpack-jarvis/bin/plugin/reporter-util'>;
}
declare module 'webpack-jarvis/bin/plugin/server.js' {
  declare module.exports: $Exports<'webpack-jarvis/bin/plugin/server'>;
}
