// flow-typed signature: 2a9aae1d36568ba5caa39f85393fa668
// flow-typed version: <<STUB>>/@glennsl/bs-jest_v^0.4.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@glennsl/bs-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@glennsl/bs-jest' {
  declare module.exports: any;
}
