// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Hello = 0;

var Index = 0;

var PostedAt = 0;

var ArticleStories = 0;

var ArticleTwoLineTitle = 0;

exports.Hello = Hello;
exports.Index = Index;
exports.PostedAt = PostedAt;
exports.ArticleStories = ArticleStories;
exports.ArticleTwoLineTitle = ArticleTwoLineTitle;
/* No side effect */
