// flow-typed signature: 7d1e56fe419f70b910aabc5b9c8e2fce
// flow-typed version: <<STUB>>/@zeit/next-less_v^0.3.1-canary.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/next-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/next-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@zeit/next-less/index' {
  declare module.exports: $Exports<'@zeit/next-less'>;
}
declare module '@zeit/next-less/index.js' {
  declare module.exports: $Exports<'@zeit/next-less'>;
}
