// flow-typed signature: 055c185ca5336d2f2cc87cf2790f6a64
// flow-typed version: <<STUB>>/@rej156/react-mde_v^5.5.6/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rej156/react-mde'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rej156/react-mde' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rej156/react-mde/lib/js/commands/boldCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/checkListCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/codeCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/headerCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/imageCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/index' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/italicCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/linkCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/orderedCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/quoteCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/strikethroughCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/tabCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/commands/unorderedListCommand' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components-layout/HorizontalLayout' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components-layout/index' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components-layout/NoPreviewLayout' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components-layout/TabbedLayout' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components-layout/VerticalLayout' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/index' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeEditor' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdePreview' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeToolbar' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeToolbarButton' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeToolbarButtonGroup' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeToolbarDropdown' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/components/MdeToolbarIcon' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/index' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/LayoutMap' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/ReactMde' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/Command' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/FunctionTypes' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/index' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/LayoutProps' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/MarkdownState' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/MdeState' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/TextInsertionResult' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/TextSelection' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/types/Word' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/util/DraftUtil' {
  declare module.exports: any;
}

declare module '@rej156/react-mde/lib/js/util/MarkdownUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rej156/react-mde/lib/js/commands/boldCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/boldCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/checkListCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/checkListCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/codeCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/codeCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/headerCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/headerCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/imageCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/imageCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/index.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/index'>;
}
declare module '@rej156/react-mde/lib/js/commands/italicCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/italicCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/linkCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/linkCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/orderedCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/orderedCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/quoteCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/quoteCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/strikethroughCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/strikethroughCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/tabCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/tabCommand'>;
}
declare module '@rej156/react-mde/lib/js/commands/unorderedListCommand.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/commands/unorderedListCommand'>;
}
declare module '@rej156/react-mde/lib/js/components-layout/HorizontalLayout.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components-layout/HorizontalLayout'>;
}
declare module '@rej156/react-mde/lib/js/components-layout/index.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components-layout/index'>;
}
declare module '@rej156/react-mde/lib/js/components-layout/NoPreviewLayout.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components-layout/NoPreviewLayout'>;
}
declare module '@rej156/react-mde/lib/js/components-layout/TabbedLayout.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components-layout/TabbedLayout'>;
}
declare module '@rej156/react-mde/lib/js/components-layout/VerticalLayout.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components-layout/VerticalLayout'>;
}
declare module '@rej156/react-mde/lib/js/components/index.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/index'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeEditor.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeEditor'>;
}
declare module '@rej156/react-mde/lib/js/components/MdePreview.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdePreview'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeToolbar.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeToolbar'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeToolbarButton.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeToolbarButton'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeToolbarButtonGroup.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeToolbarButtonGroup'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeToolbarDropdown.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeToolbarDropdown'>;
}
declare module '@rej156/react-mde/lib/js/components/MdeToolbarIcon.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/components/MdeToolbarIcon'>;
}
declare module '@rej156/react-mde/lib/js/index.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/index'>;
}
declare module '@rej156/react-mde/lib/js/LayoutMap.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/LayoutMap'>;
}
declare module '@rej156/react-mde/lib/js/ReactMde.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/ReactMde'>;
}
declare module '@rej156/react-mde/lib/js/types/Command.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/Command'>;
}
declare module '@rej156/react-mde/lib/js/types/FunctionTypes.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/FunctionTypes'>;
}
declare module '@rej156/react-mde/lib/js/types/index.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/index'>;
}
declare module '@rej156/react-mde/lib/js/types/LayoutProps.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/LayoutProps'>;
}
declare module '@rej156/react-mde/lib/js/types/MarkdownState.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/MarkdownState'>;
}
declare module '@rej156/react-mde/lib/js/types/MdeState.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/MdeState'>;
}
declare module '@rej156/react-mde/lib/js/types/TextInsertionResult.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/TextInsertionResult'>;
}
declare module '@rej156/react-mde/lib/js/types/TextSelection.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/TextSelection'>;
}
declare module '@rej156/react-mde/lib/js/types/Word.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/types/Word'>;
}
declare module '@rej156/react-mde/lib/js/util/DraftUtil.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/util/DraftUtil'>;
}
declare module '@rej156/react-mde/lib/js/util/MarkdownUtil.js' {
  declare module.exports: $Exports<'@rej156/react-mde/lib/js/util/MarkdownUtil'>;
}
