// Generated by https://pagedraw.io/pages/11563
import React from 'react'
import './1_0_1_profile_public_copy.css'

function render() {
  return (
    <div className="1_0_1_profile_public_copy-1_">
      <div className="1_0_1_profile_public_copy-0">
        <div className="1_0_1_profile_public_copy-0-0">
          <div className="1_0_1_profile_public_copy-0-0-0">
            <div className="1_0_1_profile_public_copy-0-0-0-0">
              <div className="1_0_1_profile_public_copy-path-13">
                <div className="1_0_1_profile_public_copy-0-0-0-0-0-0">
                  <div className="1_0_1_profile_public_copy-navigation-1">Source component not found</div>
                </div>
                <div className="1_0_1_profile_public_copy-0-0-0-0-0-1">
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-0">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-0-0">
                      <div className="1_0_1_profile_public_copy-path-1" />
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-1">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-1-0">
                      <img
                        src="https://pagedraw-images.s3.amazonaws.com/1680698300281489-1532956844893-B9775445-21AA-4B8A-9E26-8914C1160AA2.png"
                        className="1_0_1_profile_public_copy-_username-1"
                      />
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-1-1">
                      <div className="1_0_1_profile_public_copy-name_surname-6">Name Surname</div>
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-1-2">
                      <div className="1_0_1_profile_public_copy-lorem_ipsum_dolor_si-8">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis
                        nulla sed efficitur posuere.
                      </div>
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-2">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-2-0">
                      <div className="1_0_1_profile_public_copy-0_">0</div>
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-2-1">
                      <div className="1_0_1_profile_public_copy-articles_copy_1">articles</div>
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-3">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-3-0">
                      <div className="1_0_1_profile_public_copy-0_c">0</div>
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-3-1">
                      <div className="1_0_1_profile_public_copy-article_views_copy-1">article views</div>
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-4">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-4-0">
                      <div className="1_0_1_profile_public_copy-0_co">0</div>
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-4-1">
                      <div className="1_0_1_profile_public_copy-followers_copy_1">followers</div>
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-5">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-5-0">
                      <div className="1_0_1_profile_public_copy-0_cop">0</div>
                    </div>
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-1-5-1">
                      <div className="1_0_1_profile_public_copy-completed_requests-3">completed requests</div>
                    </div>
                  </div>
                </div>
                <div className="1_0_1_profile_public_copy-0-0-0-0-0-2">
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-0">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-0-0">
                      <img
                        src="https://pagedraw-images.s3.amazonaws.com/4298478330592280-1532956844898-56E7F80D-5914-4974-9DDB-3839CF72AFBB.png"
                        className="1_0_1_profile_public_copy-group_2"
                      />
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-1">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-1-0">
                      <div className="1_0_1_profile_public_copy-userspersonalwebsite-7">userspersonalwebsite.com</div>
                    </div>
                  </div>
                  <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-2">
                    <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-2-0">
                      <div className="1_0_1_profile_public_copy-path-9">
                        <div className="1_0_1_profile_public_copy-0-0-0-0-0-2-2-0-0-0">
                          <div className="1_0_1_profile_public_copy-follow-7">follow</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="1_0_1_profile_public_copy-0-0-0-0-0-3">
                  <div className="1_0_1_profile_public_copy-badges-1">badges</div>
                  <div className="1_0_1_profile_public_copy-contributor_copy-1">contributor</div>
                </div>
                <div className="1_0_1_profile_public_copy-0-0-0-0-0-4">
                  <img
                    src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7028474526276955-1532956845145-BE1B0977-B6CF-486F-9538-1A8694D49B5C.png"
                    className="1_0_1_profile_public_copy-group_9"
                  />
                  <img
                    src="https://pagedraw-images.s3.amazonaws.com/1536122408579863-1532956844899-1636A5EF-1146-4183-8D0A-EE57796F9DF9.png"
                    className="1_0_1_profile_public_copy-group_7"
                  />
                </div>
              </div>
              <div className="1_0_1_profile_public_copy-path-15">
                <div className="1_0_1_profile_public_copy-0-0-0-0-1-0">
                  <div className="1_0_1_profile_public_copy-articles-3">articles</div>
                  <div className="1_0_1_profile_public_copy-collections-7">collections</div>
                  <div className="1_0_1_profile_public_copy-following-1">following</div>
                </div>
                <div className="1_0_1_profile_public_copy-0-0-0-0-1-1">
                  <img
                    src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2378743333289262-1532956845168-AAFC4D46-5EAB-49F2-B63F-377AF1424EB2.png"
                    className="1_0_1_profile_public_copy-line_2"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="1_0_1_profile_public_copy-1">
        <div className="1_0_1_profile_public_copy-path-4">
          <div className="1_0_1_profile_public_copy-1-0-0">
            <div className="1_0_1_profile_public_copy-posted_3">posted 3 june 2018</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-0-1">
            <div className="1_0_1_profile_public_copy-two_line_title_two_l_copy-2">
              <div>Two line title</div>
              <div>Two line title</div>
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-0-2">
            <div className="1_0_1_profile_public_copy-lorem_ipsum_dolor_si-9">
              {
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac non magna. Nam lectus ipsum, molestie sit…'
              }
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-0-3">
            <div className="1_0_1_profile_public_copy-tags_copy-1">tags</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-0-4">
            <div className="1_0_1_profile_public_copy-makerdao_blockchai_copy-1">
              {'Makerdao • Blockchain • Ethereum • +3'}
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-0-5">
            <img
              src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7557568960498024-1532956845171-6FDA2EEA-71DA-448A-9482-456F7E74B80B.png"
              className="1_0_1_profile_public_copy-line_4"
            />
          </div>
          <div className="1_0_1_profile_public_copy-1-0-6">
            <div className="1_0_1_profile_public_copy-1-0-6-0">
              <div className="1_0_1_profile_public_copy-1-0-6-0-0">
                <img
                  src="https://pagedraw-images.s3.amazonaws.com/3852150974042155-1532956844791-6BA4900B-ECFB-43F2-9D90-D4EBF5FA54D7.png"
                  className="1_0_1_profile_public_copy-oval_copy_1"
                />
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-0-6-1">
              <div className="1_0_1_profile_public_copy-1-0-6-1-0">
                <div className="1_0_1_profile_public_copy-username_copy_2">username</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-0-6-2">
              <div className="1_0_1_profile_public_copy-1-0-6-2-0">
                <div className="1_0_1_profile_public_copy-0-4">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-0-6-2-1">
                <div className="1_0_1_profile_public_copy-up_votes-3">up votes</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-0-6-3">
              <div className="1_0_1_profile_public_copy-1-0-6-3-0">
                <div className="1_0_1_profile_public_copy-0-1">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-0-6-3-1">
                <div className="1_0_1_profile_public_copy-views_copy_2">views</div>
              </div>
            </div>
          </div>
        </div>
        <div className="1_0_1_profile_public_copy-path-8">
          <div className="1_0_1_profile_public_copy-1-1-0">
            <div className="1_0_1_profile_public_copy-posted_3_">posted 3 june 2018</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-1-1">
            <div className="1_0_1_profile_public_copy-three_line_title_thr-4">
              <div>Three line title</div>
              <div>Three line title</div>
              <div>Three line title</div>
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-1-2">
            <div className="1_0_1_profile_public_copy-lorem_ipsum_dolor_si-1">
              {
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac nn…'
              }
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-1-3">
            <div className="1_0_1_profile_public_copy-tags_copy-18">tags</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-1-4">
            <div className="1_0_1_profile_public_copy-makerdao_blockchai-1">
              {'Makerdao • Blockchain • Ethereum • +3'}
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-1-5">
            <img
              src="https://pagedraw-images.s3.amazonaws.com/1497293219532730-1532956844935-F2379EF6-98B6-461B-B36E-A8A3C36BB5BF.png"
              className="1_0_1_profile_public_copy-line_4_"
            />
          </div>
          <div className="1_0_1_profile_public_copy-1-1-6">
            <div className="1_0_1_profile_public_copy-1-1-6-0">
              <div className="1_0_1_profile_public_copy-1-1-6-0-0">
                <img
                  src="https://pagedraw-images.s3.amazonaws.com/1230730457300681-1532956844937-340083B6-D3DD-4A29-9358-2F824828F05F.png"
                  className="1_0_1_profile_public_copy-oval_copy_11"
                />
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-1-6-1">
              <div className="1_0_1_profile_public_copy-1-1-6-1-0">
                <div className="1_0_1_profile_public_copy-username_copy_2-1">username</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-1-6-2">
              <div className="1_0_1_profile_public_copy-1-1-6-2-0">
                <div className="1_0_1_profile_public_copy-0-12">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-1-6-2-1">
                <div className="1_0_1_profile_public_copy-up_votes-1">up votes</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-1-6-3">
              <div className="1_0_1_profile_public_copy-1-1-6-3-0">
                <div className="1_0_1_profile_public_copy-0-2">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-1-6-3-1">
                <div className="1_0_1_profile_public_copy-views_copy_2-7">views</div>
              </div>
            </div>
          </div>
        </div>
        <div className="1_0_1_profile_public_copy-path-12">
          <div className="1_0_1_profile_public_copy-1-2-0">
            <div className="1_0_1_profile_public_copy-posted_3_j">posted 3 june 2018</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-2-1">
            <div className="1_0_1_profile_public_copy-two_line_title_two_l_copy_2">
              <div>Two line title</div>
              <div>Two line title</div>
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-2-2">
            <div className="1_0_1_profile_public_copy-lorem_ipsum_dolor_si_copy-4">
              {
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac non magna. Nam lectus ipsum, molestie sit…'
              }
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-2-3">
            <div className="1_0_1_profile_public_copy-tags_copy-7">tags</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-2-4">
            <div className="1_0_1_profile_public_copy-makerdao_blockchai_copy-7">
              {'Makerdao • Blockchain • Ethereum • +3'}
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-2-5">
            <img
              src="https://pagedraw-images.s3.amazonaws.com/4799756645534922-1532956844784-940E48A0-246D-4E61-BF37-363F4AB6A87E.png"
              className="1_0_1_profile_public_copy-line_4_c"
            />
          </div>
          <div className="1_0_1_profile_public_copy-1-2-6">
            <div className="1_0_1_profile_public_copy-1-2-6-0">
              <div className="1_0_1_profile_public_copy-1-2-6-0-0">
                <img
                  src="https://pagedraw-images.s3.amazonaws.com/1598977968766246-1532956844793-5102C54B-D6CB-4A36-B7B6-E09D6AE11806.png"
                  className="1_0_1_profile_public_copy-oval_copy_11-1"
                />
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-2-6-1">
              <div className="1_0_1_profile_public_copy-1-2-6-1-0">
                <div className="1_0_1_profile_public_copy-username_copy_2-15">username</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-2-6-2">
              <div className="1_0_1_profile_public_copy-1-2-6-2-0">
                <div className="1_0_1_profile_public_copy-0-11">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-2-6-2-1">
                <div className="1_0_1_profile_public_copy-up_votes-13">up votes</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-2-6-3">
              <div className="1_0_1_profile_public_copy-1-2-6-3-0">
                <div className="1_0_1_profile_public_copy-0-3">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-2-6-3-1">
                <div className="1_0_1_profile_public_copy-views_copy_2-8">views</div>
              </div>
            </div>
          </div>
        </div>
        <div className="1_0_1_profile_public_copy-path-126">
          <div className="1_0_1_profile_public_copy-1-3-0">
            <div className="1_0_1_profile_public_copy-path-84" />
          </div>
          <div className="1_0_1_profile_public_copy-1-3-1">
            <div className="1_0_1_profile_public_copy-posted_3_ju">posted 3 june 2018</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-3-2">
            <div className="1_0_1_profile_public_copy-three_line_title_thr-1">
              <div>Three line title</div>
              <div>Three line title</div>
              <div>Three line title</div>
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-3-3">
            <div className="1_0_1_profile_public_copy-two_line_description-4">
              <div>Two line description</div>
              <div>Two line description</div>
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-3-4">
            <div className="1_0_1_profile_public_copy-tags_copy-10">tags</div>
          </div>
          <div className="1_0_1_profile_public_copy-1-3-5">
            <div className="1_0_1_profile_public_copy-makerdao_blockchai_copy-6">
              {'Makerdao • Blockchain • Ethereum • +3'}
            </div>
          </div>
          <div className="1_0_1_profile_public_copy-1-3-6">
            <img
              src="https://pagedraw-images.s3.amazonaws.com/1011852032604708-1532956844939-4C9EDB8B-708B-4E6F-A488-0441DEBCEEE2.png"
              className="1_0_1_profile_public_copy-line_4_co"
            />
          </div>
          <div className="1_0_1_profile_public_copy-1-3-7">
            <div className="1_0_1_profile_public_copy-1-3-7-0">
              <div className="1_0_1_profile_public_copy-1-3-7-0-0">
                <img
                  src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1843727107172726-1532956845140-A677A941-616C-48B9-9347-EAD888D6E8C9.png"
                  className="1_0_1_profile_public_copy-oval_copy_11-18"
                />
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-3-7-1">
              <div className="1_0_1_profile_public_copy-1-3-7-1-0">
                <div className="1_0_1_profile_public_copy-username_copy_2-16">username</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-3-7-2">
              <div className="1_0_1_profile_public_copy-1-3-7-2-0">
                <div className="1_0_1_profile_public_copy-0-10">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-3-7-2-1">
                <div className="1_0_1_profile_public_copy-up_votes-31">up votes</div>
              </div>
            </div>
            <div className="1_0_1_profile_public_copy-1-3-7-3">
              <div className="1_0_1_profile_public_copy-1-3-7-3-0">
                <div className="1_0_1_profile_public_copy-0-14">0</div>
              </div>
              <div className="1_0_1_profile_public_copy-1-3-7-3-1">
                <div className="1_0_1_profile_public_copy-views_copy_2-1">views</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="1_0_1_profile_public_copy-2" />
    </div>
  )
}

export default function(props) {
  return render.apply({ props: props })
}
