// Generated by https://pagedraw.io/pages/9527
import React from 'react';
import './app_no_best_price_free_delivery.css';


function render() {
    return <div className="app_no_best_price_free_delivery-app_no_best_price_free_delivery-0">
        <div className="app_no_best_price_free_delivery-0">
            <div className="app_no_best_price_free_delivery-close_button-0">
                <div className="app_no_best_price_free_delivery-0-0-0">
                    <div className="app_no_best_price_free_delivery-menu_button_bg-00">
                        <div className="app_no_best_price_free_delivery-0-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-menu_button_bg-0">
                                <div className="app_no_best_price_free_delivery-0-0-0-0-0-0-0">
                                    <div className="app_no_best_price_free_delivery-close_icon-0">
                                        <div className="app_no_best_price_free_delivery-0-0-0-0-0-0-0-0-0">
                                            <div className="app_no_best_price_free_delivery-0-0-0-0-0-0-0-0-0-0">
                                                <div className="app_no_best_price_free_delivery-rectangle-0" /> 
                                                <div className="app_no_best_price_free_delivery-rectangle-00" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="app_no_best_price_free_delivery-0-1">
                <div className="app_no_best_price_free_delivery-0-1-0">
                    <div className="app_no_best_price_free_delivery-0-1-0-0">
                        <div className="app_no_best_price_free_delivery-roboto_big_title-0">
                            Filters
                        </div>
                        <div className="app_no_best_price_free_delivery-roboto_big_title-00" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-1">
            <div className="app_no_best_price_free_delivery-1-0">
                <div className="app_no_best_price_free_delivery-1-0-0">
                    <div className="app_no_best_price_free_delivery-roboto_small-00">
                        <div className="app_no_best_price_free_delivery-1-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-roboto_small-0">
                                Best Price Only
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="app_no_best_price_free_delivery-b-4">
                Source component not found
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-2">
            <div className="app_no_best_price_free_delivery-roboto_small_title-00">
                <div className="app_no_best_price_free_delivery-2-0-0">
                    <div className="app_no_best_price_free_delivery-roboto_small_title-0">
                        Show items in
                    </div>
                </div>
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-3">
            <div className="app_no_best_price_free_delivery-3-0">
                <div className="app_no_best_price_free_delivery-3-0-0">
                    <div className="app_no_best_price_free_delivery-checkbox-0">
                        <div className="app_no_best_price_free_delivery-3-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-3-0-0-0-0-0">
                                <div className="app_no_best_price_free_delivery-rectangle_2" /> 
                                <div className="app_no_best_price_free_delivery-option_off-0" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="app_no_best_price_free_delivery-roboto_body-0">
                <div className="app_no_best_price_free_delivery-3-1-0">
                    <div className="app_no_best_price_free_delivery-us-0">
                        US
                    </div>
                </div>
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-4">
            <div className="app_no_best_price_free_delivery-4-0">
                <div className="app_no_best_price_free_delivery-4-0-0">
                    <div className="app_no_best_price_free_delivery-option_on-0">
                        <div className="app_no_best_price_free_delivery-4-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-rectangle_2-0">
                                <div className="app_no_best_price_free_delivery-4-0-0-0-0-0-0">
                                    <div className="app_no_best_price_free_delivery-checkbox-00" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="app_no_best_price_free_delivery-roboto_body-00">
                <div className="app_no_best_price_free_delivery-4-1-0">
                    <div className="app_no_best_price_free_delivery-europe-0">
                        Europe
                    </div>
                </div>
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-5">
            <div className="app_no_best_price_free_delivery-roboto_small_title-0000">
                <div className="app_no_best_price_free_delivery-5-0-0">
                    <div className="app_no_best_price_free_delivery-roboto_small_title-000">
                        Only show
                    </div>
                </div>
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-6">
            <div className="app_no_best_price_free_delivery-6-0">
                <div className="app_no_best_price_free_delivery-6-0-0">
                    <div className="app_no_best_price_free_delivery-roboto_body-000">
                        <div className="app_no_best_price_free_delivery-6-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-free_delivery-0">
                                Free Delivery
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="app_no_best_price_free_delivery-b-1">
                Source component not found
            </div>
        </div>
        <div className="app_no_best_price_free_delivery-7">
            <div className="app_no_best_price_free_delivery-rectangle-000">
                <div className="app_no_best_price_free_delivery-7-0-0">
                    <div className="app_no_best_price_free_delivery-main_button_active-0">
                        <div className="app_no_best_price_free_delivery-7-0-0-0-0">
                            <div className="app_no_best_price_free_delivery-button-0">
                                <div className="app_no_best_price_free_delivery-7-0-0-0-0-0-0">
                                    <div className="app_no_best_price_free_delivery-filter-0">
                                        Filter
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
