// Generated by https://pagedraw.io/pages/11218
import React from 'react';
import './articles.css';


function render() {
    return <div className="articles-articles-1">
        <div className="articles-0">
            <div className="articles-path-3">
                <div className="articles-0-0-0">
                    <div className="articles-posted_3">posted 3 june 2018</div>
                </div>
                <div className="articles-0-0-1">
                    <div className="articles-two_line_title_two_l_copy-1">
                        <div>Two line title</div>
                        <div>Two line title</div>
                    </div>
                </div>
                <div className="articles-0-0-2">
                    <div className="articles-three_line_descripti_copy-1">
                        <div>Three line description</div>
                        <div>Three line description</div>
                        <div>Three line description</div>
                    </div>
                </div>
                <div className="articles-0-0-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2534017087978734-1531049880527-900E794B-60FC-4FA7-A677-24647C609992.png" className="articles-line_4" /> 
                </div>
                <div className="articles-0-0-4">
                    <div className="articles-0-0-4-0">
                        <div className="articles-0-0-4-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3530107108107375-1531049880528-093E1245-F5F7-44E8-AD88-CA742897C6C3.png" className="articles-oval_copy_1" /> 
                        </div>
                    </div>
                    <div className="articles-0-0-4-1">
                        <div className="articles-0-0-4-1-0">
                            <div className="articles-username_copy_2">username</div>
                        </div>
                    </div>
                    <div className="articles-0-0-4-2">
                        <div className="articles-0-0-4-2-0">
                            <div className="articles-0-3">0</div>
                        </div>
                        <div className="articles-0-0-4-2-1">
                            <div className="articles-up_votes-8">up votes</div>
                        </div>
                    </div>
                    <div className="articles-0-0-4-3">
                        <div className="articles-0-0-4-3-0">
                            <div className="articles-0-1">0</div>
                        </div>
                        <div className="articles-0-0-4-3-1">
                            <div className="articles-views_copy_2">views</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="articles-path-9">
                <div className="articles-0-1-0">
                    <div className="articles-posted_3_">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-0-1-1">
                    <div className="articles-three_line_title_thr-4">
                        <div>Three line title</div>
                        <div>Three line title</div>
                        <div>Three line title</div>
                    </div>
                </div>
                <div className="articles-0-1-2">
                    <div className="articles-two_line_description-1">
                        <div>Two line description</div>
                        <div>Two line description</div>
                    </div>
                </div>
                <div className="articles-0-1-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5640930725129996-1531049878233-6ADA0773-7AB9-4C5E-B25F-D4161F5498BB.png" className="articles-line_4_" /> 
                </div>
                <div className="articles-0-1-4">
                    <div className="articles-0-1-4-0">
                        <div className="articles-0-1-4-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1032942010733070-1531049878239-46494B0D-12E7-4909-B51C-D5573E975215.png" className="articles-oval_copy_9" /> 
                        </div>
                    </div>
                    <div className="articles-0-1-4-1">
                        <div className="articles-0-1-4-1-0">
                            <div className="articles-username-7">username</div>
                        </div>
                    </div>
                    <div className="articles-0-1-4-2">
                        <div className="articles-0-1-4-2-0">
                            <div className="articles-0-6">0</div>
                        </div>
                        <div className="articles-0-1-4-2-1">
                            <div className="articles-up_votes-1">up votes</div>
                        </div>
                    </div>
                    <div className="articles-0-1-4-3">
                        <div className="articles-0-1-4-3-0">
                            <div className="articles-0-9">0</div>
                        </div>
                        <div className="articles-0-1-4-3-1">
                            <div className="articles-views_copy_2-1">views</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="articles-1">
            <div className="articles-path-35">
                <div className="articles-1-0-0">
                    <div className="articles-posted_3_j">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-1-0-1">
                    <div className="articles-two_line_title_two_l_copy-13">
                        <div>Two line title</div>
                        <div>Two line title</div>
                    </div>
                </div>
                <div className="articles-1-0-2">
                    <div className="articles-lorem_ipsum_dolor_si-1">
                        {"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac non magna. Nam lectus ipsum, molestie sit…"}
                    </div>
                </div>
                <div className="articles-1-0-3">
                    <div className="articles-tags_copy-1">tags</div>
                </div>
                <div className="articles-1-0-4">
                    <div className="articles-makerdao_blockchai_copy-1">
                        {"Makerdao • Blockchain • Ethereum • +3"}
                    </div>
                </div>
                <div className="articles-1-0-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9683946169503110-1531049878242-C731EA57-4043-4F27-95FE-5621359956C2.png" className="articles-line_4_c" /> 
                </div>
                <div className="articles-1-0-6">
                    <div className="articles-1-0-6-0">
                        <div className="articles-1-0-6-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1676254050917358-1531049878244-749BBE15-CCAE-4CA3-BCA5-CFD2044E7275.png" className="articles-oval_copy_11" /> 
                        </div>
                    </div>
                    <div className="articles-1-0-6-1">
                        <div className="articles-1-0-6-1-0">
                            <div className="articles-username_copy_2-4">username</div>
                        </div>
                    </div>
                    <div className="articles-1-0-6-2">
                        <div className="articles-1-0-6-2-0">
                            <div className="articles-0-67">0</div>
                        </div>
                        <div className="articles-1-0-6-2-1">
                            <div className="articles-up_votes-7">up votes</div>
                        </div>
                    </div>
                    <div className="articles-1-0-6-3">
                        <div className="articles-1-0-6-3-0">
                            <div className="articles-0-12">0</div>
                        </div>
                        <div className="articles-1-0-6-3-1">
                            <div className="articles-views_copy_2-7">views</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="articles-path-98">
                <div className="articles-1-1-0">
                    <div className="articles-posted_3_ju">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-1-1-1">
                    <div className="articles-three_line_title_thr-44">
                        <div>Three line title</div>
                        <div>Three line title</div>
                        <div>Three line title</div>
                    </div>
                </div>
                <div className="articles-1-1-2">
                    <div className="articles-lorem_ipsum_dolor_si-10">
                        {"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac nn…"}
                    </div>
                </div>
                <div className="articles-1-1-3">
                    <div className="articles-tags_copy-4">tags</div>
                </div>
                <div className="articles-1-1-4">
                    <div className="articles-makerdao_blockchai-1">
                        {"Makerdao • Blockchain • Ethereum • +3"}
                    </div>
                </div>
                <div className="articles-1-1-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1121386699963966-1531049878247-8E104B6B-7E9D-4B63-88E1-9D0BAEDF9779.png" className="articles-line_4_co" /> 
                </div>
                <div className="articles-1-1-6">
                    <div className="articles-1-1-6-0">
                        <div className="articles-1-1-6-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4125865301740304-1531049878248-07CA5A7B-9333-4AAA-9917-824A83B7041E.png" className="articles-oval_copy_11-4" /> 
                        </div>
                    </div>
                    <div className="articles-1-1-6-1">
                        <div className="articles-1-1-6-1-0">
                            <div className="articles-username_copy_2-49">username</div>
                        </div>
                    </div>
                    <div className="articles-1-1-6-2">
                        <div className="articles-1-1-6-2-0">
                            <div className="articles-0-17">0</div>
                        </div>
                        <div className="articles-1-1-6-2-1">
                            <div className="articles-up_votes-11">up votes</div>
                        </div>
                    </div>
                    <div className="articles-1-1-6-3">
                        <div className="articles-1-1-6-3-0">
                            <div className="articles-0-10">0</div>
                        </div>
                        <div className="articles-1-1-6-3-1">
                            <div className="articles-views_copy_2-8">views</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="articles-path-36">
                <div className="articles-1-2-0">
                    <div className="articles-path-7" /> 
                </div>
                <div className="articles-1-2-1">
                    <div className="articles-posted_3_jun">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-1-2-2">
                    <div className="articles-three_line_title_thr-2">
                        <div>Three line title</div>
                        <div>Three line title</div>
                        <div>Three line title</div>
                    </div>
                </div>
                <div className="articles-1-2-3">
                    <div className="articles-two_line_description-10">
                        <div>Two line description</div>
                        <div>Two line description</div>
                    </div>
                </div>
                <div className="articles-1-2-4">
                    <div className="articles-tags_copy-14">tags</div>
                </div>
                <div className="articles-1-2-5">
                    <div className="articles-makerdao_blockchai_copy-3">
                        {"Makerdao • Blockchain • Ethereum • +3"}
                    </div>
                </div>
                <div className="articles-1-2-6">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1193392343955411-1531049878250-05550BD0-E0EB-4678-859F-9281D195BD94.png" className="articles-line_4_cop" /> 
                </div>
                <div className="articles-1-2-7">
                    <div className="articles-1-2-7-0">
                        <div className="articles-1-2-7-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1583325928116304-1531049878253-F221935D-A694-4829-8F1C-E85985E35592.png" className="articles-oval_copy_11-1" /> 
                        </div>
                    </div>
                    <div className="articles-1-2-7-1">
                        <div className="articles-1-2-7-1-0">
                            <div className="articles-username_copy_2-6">username</div>
                        </div>
                    </div>
                    <div className="articles-1-2-7-2">
                        <div className="articles-1-2-7-2-0">
                            <div className="articles-0-11">0</div>
                        </div>
                        <div className="articles-1-2-7-2-1">
                            <div className="articles-up_votes-13">up votes</div>
                        </div>
                    </div>
                    <div className="articles-1-2-7-3">
                        <div className="articles-1-2-7-3-0">
                            <div className="articles-0-105">0</div>
                        </div>
                        <div className="articles-1-2-7-3-1">
                            <div className="articles-views_copy_2-4">views</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="articles-2">
            <div className="articles-path-1">
                <div className="articles-2-0-0">
                    <div className="articles-posted_3_june">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-2-0-1">
                    <div className="articles-long_title-7">Long title</div>
                </div>
                <div className="articles-2-0-2">
                    <div className="articles-lorem_ipsum_dolor_si-5">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper semper. Morbi mollis mauris quis orci tristique posuere ac non magna. Nam lectus ipsum, molestie si.
                    </div>
                </div>
                <div className="articles-2-0-3">
                    <div className="articles-tags_copy-6">tags</div>
                </div>
                <div className="articles-2-0-4">
                    <div className="articles-makerdao_blockchai-5">
                        {"Makerdao • Blockchain • Ethereum"}
                    </div>
                </div>
                <div className="articles-2-0-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4870037420660682-1531049878259-B695BAE6-A764-45B2-966B-5D2433FE8CC0.png" className="articles-line_4_copy" /> 
                </div>
                <div className="articles-2-0-6">
                    <div className="articles-2-0-6-0">
                        <div className="articles-2-0-6-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3393930520904364-1531049878254-02574CE3-78EA-4EB6-AB2A-330E479674FD.png" className="articles-bitmap_copy-3" /> 
                        </div>
                    </div>
                    <div className="articles-2-0-6-1">
                        <div className="articles-2-0-6-1-0">
                            <div className="articles-username_copy_2-7">username</div>
                        </div>
                    </div>
                    <div className="articles-2-0-6-2">
                        <div className="articles-2-0-6-2-0">
                            <div className="articles-0_">0</div>
                        </div>
                        <div className="articles-2-0-6-2-1">
                            <div className="articles-up_votes_copy-2">up votes</div>
                        </div>
                    </div>
                    <div className="articles-2-0-6-3">
                        <div className="articles-2-0-6-3-0">
                            <div className="articles-0_c">0</div>
                        </div>
                        <div className="articles-2-0-6-3-1">
                            <div className="articles-views_copy_3">views</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="articles-path-13">
                <div className="articles-2-1-0">
                    <div className="articles-path-11" /> 
                </div>
                <div className="articles-2-1-1">
                    <div className="articles-posted_3_june_">
                        posted 3 june 2018
                    </div>
                </div>
                <div className="articles-2-1-2">
                    <div className="articles-long_title_copy-1">
                        Long title
                    </div>
                </div>
                <div className="articles-2-1-3">
                    <div className="articles-lorem_ipsum_dolor_si-13">
                        {"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed cursus purus. In facilisis nulla sed efficitur posuere. Maecenas vestibulum elementum interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non eleifend ex, eu interdum justo. Duis dolor nibh, ornare eu egestas non, dapibus ornare nisl. Nunc nec dui id magna ullamcorper…"}
                    </div>
                </div>
                <div className="articles-2-1-4">
                    <div className="articles-tags_copy-5">tags</div>
                </div>
                <div className="articles-2-1-5">
                    <div className="articles-makerdao_blockchai-7">
                        {"Makerdao • Blockchain • Ethereum"}
                    </div>
                </div>
                <div className="articles-2-1-6">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1676558472224484-1531049878262-E2AC3EE7-9264-4188-8231-A8FA150339C5.png" className="articles-line_4_copy_" /> 
                </div>
                <div className="articles-2-1-7">
                    <div className="articles-2-1-7-0">
                        <div className="articles-2-1-7-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2059208771716972-1531049878256-E47C2682-2B4B-4A82-98C7-6144598B5964.png" className="articles-bitmap_copy_2" /> 
                        </div>
                    </div>
                    <div className="articles-2-1-7-1">
                        <div className="articles-2-1-7-1-0">
                            <div className="articles-username_copy_3">username</div>
                        </div>
                    </div>
                    <div className="articles-2-1-7-2">
                        <div className="articles-2-1-7-2-0">
                            <div className="articles-0_co">0</div>
                        </div>
                        <div className="articles-2-1-7-2-1">
                            <div className="articles-up_votes_copy_2">up votes</div>
                        </div>
                    </div>
                    <div className="articles-2-1-7-3">
                        <div className="articles-2-1-7-3-0">
                            <div className="articles-0_cop">0</div>
                        </div>
                        <div className="articles-2-1-7-3-1">
                            <div className="articles-views_copy_4">views</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
