// Generated by https://pagedraw.io/pages/11218
import React from 'react';
import './collections.css';


function render() {
    return <div className="collections-collections-4">
        <div className="collections-0">
            <div className="collections-path-9">
                <div className="collections-0-0-0">
                    <div className="collections-collection-1">collection</div>
                </div>
                <div className="collections-0-0-1">
                    <div className="collections-0-0-1-0">
                        <div className="collections-0-0-1-0-0">
                            <div className="collections-0-0-1-0-0-0">
                                <div className="collections-collection_lorem_ips-5">
                                    Collection Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </div>
                                <div className="collections-two_line_description-1">
                                    <div>Two line description</div>
                                    <div>Two line description</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="collections-0-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9351896987129640-1531049878275-BF0A18D8-8DB3-4CC1-963A-03C27773A445.png" className="collections-group_8" /> 
                </div>
                <div className="collections-0-0-3">
                    <div className="collections-updated_3">
                        updated 3 days ago
                    </div>
                </div>
                <div className="collections-0-0-4">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2316932796739945-1531049878496-851C5BFD-82BB-4BD1-9F50-553D33EC8C45.png" className="collections-line_4" /> 
                </div>
                <div className="collections-0-0-5">
                    <div className="collections-0-1">0</div>
                    <div className="collections-0-11">0</div>
                    <div className="collections-0-12">0</div>
                </div>
                <div className="collections-0-0-6">
                    <div className="collections-up_votes_copy_6">up votes</div>
                    <div className="collections-articles_copy_1">articles</div>
                    <div className="collections-followers_copy_1">
                        followers
                    </div>
                </div>
            </div>
            <div className="collections-path-97">
                <div className="collections-0-1-0">
                    <div className="collections-collection_copy-1">
                        collection
                    </div>
                </div>
                <div className="collections-0-1-1">
                    <div className="collections-lorem_ipsum_dolor_si-1">
                        Lorem ipsum dolor sit amet
                    </div>
                </div>
                <div className="collections-0-1-2">
                    <div className="collections-two_line_description_copy-8">
                        <div>Two line description</div>
                        <div>Two line description</div>
                    </div>
                </div>
                <div className="collections-0-1-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1161297267688066-1531049878278-B816B6ED-0DE2-4183-B55E-9E77055E46A7.png" className="collections-group_8_" /> 
                </div>
                <div className="collections-0-1-4">
                    <div className="collections-updated_3_">
                        updated 3 days ago
                    </div>
                </div>
                <div className="collections-0-1-5">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1308737010538425-1531049878499-F0C2CD8C-1250-4FD0-B760-DB94ED0889B3.png" className="collections-line_4_" /> 
                </div>
                <div className="collections-0-1-6">
                    <div className="collections-0_">0</div>
                    <div className="collections-0_c">0</div>
                    <div className="collections-0_co">0</div>
                </div>
                <div className="collections-0-1-7">
                    <div className="collections-up_votes_copy_9">up votes</div>
                    <div className="collections-articles_copy_13">
                        articles
                    </div>
                    <div className="collections-followers_copy_13">
                        followers
                    </div>
                </div>
            </div>
            <div className="collections-0-2">
                <div className="collections-0-2-0">
                    <div className="collections-path-91">
                        <div className="collections-0-2-0-0-0">
                            <div className="collections-collection-9">collection</div>
                        </div>
                        <div className="collections-0-2-0-0-1">
                            <div className="collections-lorem_ipsum_dolor_si-10">
                                Lorem ipsum dolor sit amet
                            </div>
                        </div>
                        <div className="collections-0-2-0-0-2">
                            <div className="collections-two_line_description_copy-7">
                                <div>Two line description</div>
                                <div>Two line description</div>
                            </div>
                        </div>
                        <div className="collections-0-2-0-0-3">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7057559644219577-1531049878279-883CB244-D292-4DF8-B772-CE957F931EA4.png" className="collections-oval_copy_1" /> 
                        </div>
                        <div className="collections-0-2-0-0-4">
                            <div className="collections-updated_3_d">
                                updated 3 days ago
                            </div>
                        </div>
                    </div>
                </div>
                <div className="collections-0-2-1">
                    <div className="collections-path-1">
                        <div className="collections-0-2-1-0-0">
                            <div className="collections-0-13">0</div>
                            <div className="collections-0-6">0</div>
                            <div className="collections-0-60">0</div>
                        </div>
                        <div className="collections-0-2-1-0-1">
                            <div className="collections-up_votes_copy_6-2">
                                up votes
                            </div>
                            <div className="collections-articles_copy_10">
                                articles
                            </div>
                            <div className="collections-followers_copy_10">
                                followers
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="collections-1">
            <div className="collections-path-8">
                <div className="collections-1-0-0">
                    <div className="collections-collection_copy_2">
                        collection
                    </div>
                </div>
                <div className="collections-1-0-1">
                    <div className="collections-1-0-1-0">
                        <div className="collections-1-0-1-0-0">
                            <div className="collections-1-0-1-0-0-0">
                                <div className="collections-collection_lorem_ips-1">
                                    Collection Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </div>
                                <div className="collections-two_line_description-7">
                                    <div>Two line description</div>
                                    <div>Two line description</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="collections-1-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1023039724855441-1531049878276-31E29A6D-756E-4C1E-B22B-F19EF33BC625.png" className="collections-group_8_c" /> 
                </div>
                <div className="collections-1-0-3">
                    <div className="collections-updated_3_da">
                        updated 3 days ago
                    </div>
                </div>
                <div className="collections-1-0-4">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9849820058278676-1531049878497-EFD6809F-4F98-413C-8091-5F282B8C4F96.png" className="collections-line_4_c" /> 
                </div>
                <div className="collections-1-0-5">
                    <div className="collections-0_cop">0</div>
                    <div className="collections-0_copy">0</div>
                    <div className="collections-0_copy-1">0</div>
                </div>
                <div className="collections-1-0-6">
                    <div className="collections-up_votes_copy_7">up votes</div>
                    <div className="collections-articles_copy_11">
                        articles
                    </div>
                    <div className="collections-followers_copy_11">
                        followers
                    </div>
                </div>
            </div>
            <div className="collections-1-1">
                <div className="collections-1-1-0">
                    <div className="collections-path-15">
                        <div className="collections-1-1-0-0-0">
                            <div className="collections-collection_copy_3">
                                collection
                            </div>
                        </div>
                        <div className="collections-1-1-0-0-1">
                            <div className="collections-lorem_ipsum_dolor_si_copy-1">
                                Lorem ipsum dolor sit amet
                            </div>
                        </div>
                        <div className="collections-1-1-0-0-2">
                            <div className="collections-two_line_description_copy_2">
                                <div>Two line description</div>
                                <div>Two line description</div>
                            </div>
                        </div>
                        <div className="collections-1-1-0-0-3">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6587945559944910-1531049878281-A3038242-9D05-471A-AD6B-1F4D25496892.png" className="collections-oval_copy_12" /> 
                        </div>
                        <div className="collections-1-1-0-0-4">
                            <div className="collections-updated_3_day">
                                updated 3 days ago
                            </div>
                        </div>
                    </div>
                </div>
                <div className="collections-1-1-1">
                    <div className="collections-path-11">
                        <div className="collections-1-1-1-0-0">
                            <div className="collections-0_copy_">0</div>
                            <div className="collections-0_copy_5">0</div>
                            <div className="collections-0_copy_4">0</div>
                        </div>
                        <div className="collections-1-1-1-0-1">
                            <div className="collections-up_votes_copy_8">up votes</div>
                            <div className="collections-articles_copy_12">
                                articles
                            </div>
                            <div className="collections-followers_copy_12">
                                followers
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
