// Generated by https://pagedraw.io/pages/8998
import React from 'react';
import styled, {injectGlobal} from 'styled-components';

injectGlobal`
    * {
        box-sizing: border-box;
    }
    
    body {
        margin: 0;
    }
    
    button:hover {
        cursor: pointer;
    }
    
    a {
        text-decoration: none;
        color: inherit;
    }
    
    .pd-onhover-parent >.pd-onhover {
        display: none;
    }
    
    .pd-onhover-parent:hover > * {
        display: none;
    }
    
    .pd-onhover-parent:hover > .pd-onhover {
        display: flex;
    }
    
    .pd-onactive-parent > .pd-onactive {
        display: none;
    }
    
    .pd-onactive-parent:active > * {
        display: none;
    }
    
    .pd-onactive-parent:active > .pd-onactive {
        display: flex;
    }
    
    .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
        display: none;
    }
`
const Kaurilandingpage_kaurilandingpage_1 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    background: #FFFFFF;
    min-height: 100vh;
`

const Kaurilandingpage_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_0_0 = styled.div`
    display: flex;
    flex-direction: column;
`

const Kaurilandingpage_0_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_0_0_0_0 = styled.div`
    width: 1680px;
    height: 1569px;
    flex-shrink: 0;
    position: relative;
`

const Kaurilandingpage_screen_size_group_3 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    padding-bottom: 2px;
    position: absolute;
    top: 0px;
    left: 0px;
`

const Kaurilandingpage_0_0_0_0_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_bitmap_7 = styled.div`
    display: flex;
    flex-direction: column;
    padding-top: 24px;
    padding-bottom: 346px;
    background-image: url('https://pagedraw-images.s3-us-west-1.amazonaws.com/7810014347771497-1522016391453-D4E25659-D1ED-49A2-AECC-AA4D947AC22A.png');
    background-size: 100% 100%;
    background-attachment: fixed;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0 = styled.div`
    display: flex;
    padding-left: 153px;
    padding-right: 546px;
`

const Kaurilandingpage_kauri_copy_5 = styled.div`
    width: 51px;
    flex-shrink: 0;
    font-family: OpenSans-Bold;
    color: rgb(255, 255, 255);
    font-size: 20px;
    line-height: 23px;
    letter-spacing: -0.625px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Kaurilandingpage_the_problem_1 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 342px;
    padding-top: 2px;
    padding-bottom: 3px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: right;
    word-wrap: break-word;
    padding-right: 0.453125px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_2 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 46px;
    padding-top: 2px;
    padding-bottom: 3px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_2_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_who_is_it_for_1 = styled.div`
    width: 87px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: right;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_3 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 40px;
    padding-top: 2px;
    padding-bottom: 3px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_3_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_features_1 = styled.div`
    width: 64px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: right;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_4 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 51px;
    padding-top: 2px;
    padding-bottom: 3px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_4_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_roadmap_1 = styled.div`
    width: 71px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: right;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_5 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 46px;
    padding-top: 2px;
    padding-bottom: 3px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_0_5_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_vision_paper_1 = styled.div`
    width: 90px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: right;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_0_0_0_1 = styled.div`
    display: flex;
    margin-top: 361px;
    padding-left: 113px;
    padding-right: 1011px;
`

const Kaurilandingpage_rectangle_2 = styled.div`
    display: flex;
    flex-direction: column;
    padding-bottom: 30px;
`

const Kaurilandingpage_0_0_0_0_0_0_0_1_0_0 = styled.div`
    display: flex;
    padding-right: 413px;
`

const Kaurilandingpage_kauri_6 = styled.div`
    width: 143px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 60px;
    line-height: 68px;
    letter-spacing: -1px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_0_0_0_1_0_1 = styled.div`
    display: flex;
    margin-top: 24px;
    padding-left: 6px;
    padding-right: 8px;
`

const Kaurilandingpage_technical_support_ne_1 = styled.div`
    width: 542px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 20px;
    line-height: 23px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Kaurilandingpage_path_1 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    padding-top: 202px;
    padding-bottom: 271px;
    position: absolute;
    top: 899px;
    left: 0px;
    background: linear-gradient(0deg, #4D565A, #4D565A);
    min-height: 100vh;
`

const Kaurilandingpage_0_0_0_0_1_0 = styled.div`
    display: flex;
    padding-left: 559px;
    padding-right: 560px;
`

const Kaurilandingpage_open_support_for_ope_5 = styled.div`
    width: 561px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 40px;
    line-height: 46px;
    letter-spacing: -0.6666666px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_0_0_0_0_1_1 = styled.div`
    display: flex;
    margin-top: 97px;
    padding-left: 406px;
    padding-right: 406px;
`

const Kaurilandingpage_open_source_support_1 = styled.div`
    width: 868px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_1 = styled.div`
    display: flex;
`

const Kaurilandingpage_path_4 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    padding-top: 158px;
    padding-bottom: 188px;
    background: rgb(104, 142, 138);
`

const Kaurilandingpage_1_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_1_0_0_0 = styled.div`
    height: 0px;
    flex-grow: 0.4095238095238095;
    flex-basis: 0px;
`

const Kaurilandingpage_who_is_kauri_for__1 = styled.div`
    flex-grow: 0.18095238095238095;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 40px;
    line-height: 46px;
    letter-spacing: -0.6666667px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_1_0_0_2 = styled.div`
    height: 0px;
    flex-grow: 0.4095238095238095;
    flex-basis: 0px;
`

const Kaurilandingpage_1_0_1 = styled.div`
    display: flex;
    margin-top: 107px;
`

const Kaurilandingpage_1_0_1_0 = styled.div`
    height: 0px;
    flex-grow: 0.22564102564102564;
    flex-basis: 0px;
`

const Kaurilandingpage_icons8 = styled.img`
    width: 40px;
    height: 40px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_1_0_1_2 = styled.div`
    height: 0px;
    flex-grow: 0.2743589743589744;
    flex-basis: 0px;
`

const Kaurilandingpage_icons8_c = styled.img`
    width: 40px;
    height: 40px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_1_0_1_4 = styled.div`
    height: 0px;
    flex-grow: 0.27371794871794874;
    flex-basis: 0px;
`

const Kaurilandingpage_icons8_m = styled.img`
    width: 40px;
    height: 40px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_1_0_1_6 = styled.div`
    height: 0px;
    flex-grow: 0.22628205128205128;
    flex-basis: 0px;
`

const Kaurilandingpage_1_0_2 = styled.div`
    display: flex;
    margin-top: 22px;
`

const Kaurilandingpage_1_0_2_0 = styled.div`
    height: 0px;
    flex-grow: 0.21855345911949686;
    flex-basis: 0px;
`

const Kaurilandingpage_learn_get_help_1 = styled.div`
    width: 189px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 24px;
    line-height: 27px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_1_0_2_2 = styled.div`
    height: 0px;
    flex-grow: 0.24371069182389937;
    flex-basis: 0px;
`

const Kaurilandingpage_contribute_1 = styled.div`
    width: 126px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 24px;
    line-height: 27px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_1_0_2_4 = styled.div`
    height: 0px;
    flex-grow: 0.28144654088050314;
    flex-basis: 0px;
`

const Kaurilandingpage_support_8 = styled.div`
    width: 93px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(255, 255, 255);
    font-size: 24px;
    line-height: 27px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_1_0_2_6 = styled.div`
    height: 0px;
    flex-grow: 0.2562893081761006;
    flex-basis: 0px;
`

const Kaurilandingpage_1_0_3 = styled.div`
    display: flex;
    margin-top: 28px;
    padding-left: 154px;
    padding-right: 155px;
`

const Kaurilandingpage_1_0_3_0 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 0.3333333333333333;
    flex-basis: 0px;
    min-height: fit-content;
    padding-bottom: 18px;
`

const Kaurilandingpage_1_0_3_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_receive_any_level_of_1 = styled.div`
    flex-grow: 1;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_allow_kauri_s_best_p_1 = styled.div`
    flex-grow: 0.3333333333333333;
    flex-basis: 0px;
    margin-left: 32px;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_monetize_your_expert_1 = styled.div`
    flex-grow: 0.3333333333333333;
    flex-basis: 0px;
    margin-left: 31px;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_2 = styled.div`
    display: flex;
    flex-grow: 0.5577812018489985;
    flex-basis: 0px;
    min-height: fit-content;
`

const Kaurilandingpage_path_9 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    padding-top: 72px;
    padding-bottom: 146px;
    background: rgb(218, 214, 212);
`

const Kaurilandingpage_2_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_2_0_0_0 = styled.div`
    height: 0px;
    flex-grow: 0.4238095238095238;
    flex-basis: 0px;
`

const Kaurilandingpage_kauri_features_copy_1 = styled.div`
    flex-grow: 0.15476190476190477;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(30, 30, 30);
    font-size: 40px;
    line-height: 46px;
    letter-spacing: -0.6666667px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_2_0_0_2 = styled.div`
    height: 0px;
    flex-grow: 0.42142857142857143;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1 = styled.div`
    display: flex;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    margin-top: 119px;
`

const Kaurilandingpage_2_0_1_0 = styled.div`
    height: 0px;
    flex-grow: 0.4768812330009066;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1_1 = styled.div`
    display: flex;
    flex-direction: column;
`

const Kaurilandingpage_2_0_1_1_0 = styled.div`
    width: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1_1_1 = styled.div`
    display: flex;
`

const Kaurilandingpage_icons8_l = styled.img`
    width: 50px;
    height: 50px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_1_2 = styled.div`
    display: flex;
    margin-top: 8px;
`

const Kaurilandingpage_browse_1 = styled.div`
    width: 50px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(30, 30, 30);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_2_0_1_1_3 = styled.div`
    display: flex;
    margin-top: 194px;
`

const Kaurilandingpage_icons8_e = styled.img`
    width: 50px;
    height: 50px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_2 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 29px;
    padding-top: 38px;
    padding-bottom: 12px;
`

const Kaurilandingpage_2_0_1_2_0 = styled.div`
    display: flex;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
`

const Kaurilandingpage_group_3 = styled.img`
    width: 133px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_3 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 42px;
    padding-top: 86px;
    padding-bottom: 61px;
`

const Kaurilandingpage_2_0_1_3_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_2_0_1_3_0_0 = styled.div`
    width: 121px;
    height: 171px;
    flex-shrink: 0;
    position: relative;
`

const Kaurilandingpage_icons8_t = styled.img`
    width: 109px;
    height: 109px;
    flex-grow: 1;
    position: absolute;
    top: 0px;
    left: 7px;
    border-width: 0px;
`

const Kaurilandingpage_fill_3 = styled.img`
    width: 121px;
    height: 24px;
    flex-grow: 1;
    position: absolute;
    top: 100px;
    left: 0px;
    border-width: 0px;
`

const Kaurilandingpage_icons8_co = styled.img`
    width: 51px;
    height: 51px;
    flex-grow: 1;
    position: absolute;
    top: 120px;
    left: 35px;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_4 = styled.div`
    display: flex;
    flex-direction: column;
    margin-left: 40px;
    padding-top: 38px;
    padding-bottom: 12px;
`

const Kaurilandingpage_2_0_1_4_0 = styled.div`
    display: flex;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
`

const Kaurilandingpage_group_4 = styled.img`
    width: 133px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_5 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 0.050770625566636446;
    flex-basis: 0px;
    min-height: fit-content;
    margin-left: 29px;
`

const Kaurilandingpage_2_0_1_5_0 = styled.div`
    width: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1_5_1 = styled.div`
    display: flex;
    padding-left: 3px;
`

const Kaurilandingpage_icons8_a = styled.img`
    width: 50px;
    height: 50px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_5_1_1 = styled.div`
    height: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1_5_2 = styled.div`
    display: flex;
    margin-top: 8px;
`

const Kaurilandingpage_request_1 = styled.div`
    width: 56px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(30, 30, 30);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Kaurilandingpage_2_0_1_5_3 = styled.div`
    display: flex;
    margin-top: 194px;
    padding-left: 3px;
`

const Kaurilandingpage_icons8_s = styled.img`
    width: 50px;
    height: 50px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_2_0_1_5_3_1 = styled.div`
    height: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_1_6 = styled.div`
    height: 0px;
    flex-grow: 0.47234814143245696;
    flex-basis: 0px;
`

const Kaurilandingpage_2_0_2 = styled.div`
    display: flex;
    margin-top: 7px;
`

const Kaurilandingpage_2_0_2_0 = styled.div`
    height: 0px;
    flex-grow: 0.330749354005168;
    flex-basis: 0px;
`

const Kaurilandingpage_contribute_6 = styled.div`
    width: 77px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(30, 30, 30);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_2_0_2_2 = styled.div`
    height: 0px;
    flex-grow: 0.332687338501292;
    flex-basis: 0px;
`

const Kaurilandingpage_support_2 = styled.div`
    width: 55px;
    flex-shrink: 0;
    font-family: OpenSans-SemiBold;
    color: rgb(30, 30, 30);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Kaurilandingpage_2_0_2_4 = styled.div`
    height: 0px;
    flex-grow: 0.3365633074935401;
    flex-basis: 0px;
`

const Kaurilandingpage_3 = styled.div`
    display: flex;
    flex-grow: 0.4422187981510015;
    flex-basis: 0px;
    min-height: fit-content;
`

const Kaurilandingpage_path_13 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    padding-top: 95px;
    background: rgb(236, 236, 236);
`

const Kaurilandingpage_3_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_3_0_0_0 = styled.div`
    height: 0px;
    flex-grow: 0.5010033444816053;
    flex-basis: 0px;
`

const Kaurilandingpage_road_map_1 = styled.div`
    width: 185px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(30, 30, 30);
    font-size: 40px;
    line-height: 46px;
    letter-spacing: -0.6666667px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_3_0_0_2 = styled.div`
    height: 0px;
    flex-grow: 0.49899665551839467;
    flex-basis: 0px;
`

const Kaurilandingpage_3_0_1 = styled.div`
    display: flex;
    margin-top: 39px;
`

const Kaurilandingpage_3_0_1_0 = styled.div`
    height: 0px;
    flex-grow: 0.3113095238095238;
    flex-basis: 0px;
`

const Kaurilandingpage_lorem_ipsum_dolor_si_4 = styled.div`
    flex-grow: 0.37797619047619047;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(30, 30, 30);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_3_0_1_2 = styled.div`
    height: 0px;
    flex-grow: 0.3107142857142857;
    flex-basis: 0px;
`

const Kaurilandingpage_3_0_2 = styled.div`
    width: 0px;
    flex-grow: 0.18118466898954705;
    flex-basis: 0px;
`

const Kaurilandingpage_3_0_3 = styled.div`
    display: flex;
`

const Kaurilandingpage_3_0_3_0 = styled.div`
    height: 0px;
    flex-grow: 0.27177472167648986;
    flex-basis: 0px;
`

const Kaurilandingpage_phase_1 = styled.div`
    width: 51px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(63, 62, 64);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_3_0_3_2 = styled.div`
    height: 0px;
    flex-grow: 0.22789783889980353;
    flex-basis: 0px;
`

const Kaurilandingpage_phase_2 = styled.div`
    width: 51px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(63, 62, 64);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_3_0_3_4 = styled.div`
    height: 0px;
    flex-grow: 0.22855271774721678;
    flex-basis: 0px;
`

const Kaurilandingpage_phase_3 = styled.div`
    width: 51px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(63, 62, 64);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_3_0_3_6 = styled.div`
    height: 0px;
    flex-grow: 0.27177472167648986;
    flex-basis: 0px;
`

const Kaurilandingpage_3_0_4 = styled.div`
    display: flex;
    margin-top: 52px;
`

const Kaurilandingpage_3_0_4_0 = styled.div`
    height: 0px;
    flex-grow: 0.24702380952380953;
    flex-basis: 0px;
`

const Kaurilandingpage_line_7 = styled.img`
    height: 3px;
    flex-grow: 0.5059523809523809;
    flex-basis: 0px;
    border-width: 0px;
    width: 0px;
`

const Kaurilandingpage_3_0_4_2 = styled.div`
    height: 0px;
    flex-grow: 0.24702380952380953;
    flex-basis: 0px;
`

const Kaurilandingpage_3_0_5 = styled.div`
    width: 0px;
    flex-grow: 0.818815331010453;
    flex-basis: 0px;
`

const Kaurilandingpage_4 = styled.div`
    display: flex;
    margin-top: 106px;
    padding-left: 523px;
    padding-right: 522px;
`

const Kaurilandingpage_rectangle_5 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
`

const Kaurilandingpage_4_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_4_0_0_0 = styled.div`
    height: 0px;
    flex-grow: 0.32440944881889766;
    flex-basis: 0px;
`

const Kaurilandingpage_vision_paper_copy_7 = styled.div`
    flex-grow: 0.352755905511811;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(30, 30, 30);
    font-size: 40px;
    line-height: 46px;
    letter-spacing: -0.6666667px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_4_0_0_2 = styled.div`
    height: 0px;
    flex-grow: 0.3228346456692913;
    flex-basis: 0px;
`

const Kaurilandingpage_4_0_1 = styled.div`
    display: flex;
    margin-top: 32px;
`

const Kaurilandingpage_4_0_1_0 = styled.div`
    height: 0px;
    flex-grow: 0;
    flex-basis: 0px;
`

const Kaurilandingpage_lorem_ipsum_dolor_si_copy_1 = styled.div`
    flex-grow: 1;
    flex-basis: 0px;
    font-family: OpenSans-Regular;
    color: rgb(30, 30, 30);
    font-size: 16px;
    line-height: 18px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_4_0_1_2 = styled.div`
    height: 0px;
    flex-grow: 0;
    flex-basis: 0px;
`

const Kaurilandingpage_4_0_2 = styled.div`
    display: flex;
    margin-top: 98px;
`

const Kaurilandingpage_4_0_2_0 = styled.div`
    height: 0px;
    flex-grow: 0.5008517887563884;
    flex-basis: 0px;
`

const Kaurilandingpage_group_2 = styled.img`
    width: 48px;
    height: 60px;
    flex-shrink: 0;
    border-width: 0px;
`

const Kaurilandingpage_4_0_2_2 = styled.div`
    height: 0px;
    flex-grow: 0.4991482112436116;
    flex-basis: 0px;
`

const Kaurilandingpage_4_0_3 = styled.div`
    display: flex;
    margin-top: 41px;
`

const Kaurilandingpage_4_0_3_0 = styled.div`
    height: 0px;
    flex-grow: 0.5012531328320802;
    flex-basis: 0px;
`

const Kaurilandingpage_path_12 = styled.div`
    display: flex;
    flex-direction: column;
    padding-top: 11px;
    padding-bottom: 15px;
    border-radius: 4px;
    background: rgb(104, 142, 138);
`

const Kaurilandingpage_4_0_3_1_0 = styled.div`
    display: flex;
    padding-left: 81px;
    padding-right: 82px;
`

const Kaurilandingpage_view_paper_copy_5 = styled.div`
    width: 73px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_4_0_3_2 = styled.div`
    height: 0px;
    flex-grow: 0.49874686716791977;
    flex-basis: 0px;
`

const Kaurilandingpage_5 = styled.div`
    display: flex;
    margin-top: 95px;
`

const Kaurilandingpage_path_3 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    padding-top: 60px;
    padding-bottom: 68px;
    background: rgb(0, 0, 0);
`

const Kaurilandingpage_5_0_0 = styled.div`
    display: flex;
`

const Kaurilandingpage_5_0_0_0 = styled.div`
    height: 0px;
    flex-grow: 0.5003232062055591;
    flex-basis: 0px;
`

const Kaurilandingpage_subscribe_copy_4 = styled.div`
    width: 133px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 30px;
    line-height: 34px;
    letter-spacing: -0.5px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_5_0_0_2 = styled.div`
    height: 0px;
    flex-grow: 0.49967679379444085;
    flex-basis: 0px;
`

const Kaurilandingpage_5_0_1 = styled.div`
    display: flex;
    margin-top: 43px;
`

const Kaurilandingpage_5_0_1_0 = styled.div`
    height: 0px;
    flex-grow: 0.5007440476190477;
    flex-basis: 0px;
`

const Kaurilandingpage_path_43 = styled.div`
    display: flex;
    flex-direction: column;
    padding-top: 14px;
    padding-bottom: 15px;
    border-radius: 4px;
    background: rgba(216, 216, 216, 0);
    border: 1px solid #FFFFFF;
`

const Kaurilandingpage_5_0_1_1_0 = styled.div`
    display: flex;
    padding-left: 132px;
    padding-right: 130px;
`

const Kaurilandingpage_email_address_1 = styled.div`
    width: 72px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 11px;
    line-height: 13px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_5_0_1_2 = styled.div`
    height: 0px;
    flex-grow: 0.4992559523809524;
    flex-basis: 0px;
`

const Kaurilandingpage_5_0_2 = styled.div`
    display: flex;
    margin-top: 19px;
`

const Kaurilandingpage_5_0_2_0 = styled.div`
    height: 0px;
    flex-grow: 0.5006925207756233;
    flex-basis: 0px;
`

const Kaurilandingpage_path_10 = styled.div`
    display: flex;
    flex-direction: column;
    padding-top: 11px;
    padding-bottom: 15px;
    border-radius: 4px;
    background: rgb(104, 142, 138);
`

const Kaurilandingpage_5_0_2_1_0 = styled.div`
    display: flex;
    padding-left: 93px;
    padding-right: 93px;
`

const Kaurilandingpage_sign_up_1 = styled.div`
    width: 50px;
    flex-shrink: 0;
    font-family: OpenSans-Regular;
    color: rgb(255, 255, 255);
    font-size: 14px;
    line-height: 16px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
`

const Kaurilandingpage_5_0_2_2 = styled.div`
    height: 0px;
    flex-grow: 0.49930747922437674;
    flex-basis: 0px;
`

function render() {
    return <Kaurilandingpage_kaurilandingpage_1>
        <Kaurilandingpage_0>
            <Kaurilandingpage_0_0>
                <Kaurilandingpage_0_0_0>
                    <Kaurilandingpage_0_0_0_0>
                        <Kaurilandingpage_screen_size_group_3>
                            <Kaurilandingpage_0_0_0_0_0_0>
                                <Kaurilandingpage_bitmap_7>
                                    <Kaurilandingpage_0_0_0_0_0_0_0_0>
                                        <Kaurilandingpage_kauri_copy_5>
                                            Kauri
                                        </Kaurilandingpage_kauri_copy_5>
                                        <Kaurilandingpage_the_problem_1>
                                            The Problem
                                        </Kaurilandingpage_the_problem_1>
                                        <Kaurilandingpage_0_0_0_0_0_0_0_0_2>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_0_2_0>
                                                <Kaurilandingpage_who_is_it_for_1>
                                                    Who is it for
                                                </Kaurilandingpage_who_is_it_for_1>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_0_2_0>
                                        </Kaurilandingpage_0_0_0_0_0_0_0_0_2>
                                        <Kaurilandingpage_0_0_0_0_0_0_0_0_3>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_0_3_0>
                                                <Kaurilandingpage_features_1>
                                                    Features
                                                </Kaurilandingpage_features_1>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_0_3_0>
                                        </Kaurilandingpage_0_0_0_0_0_0_0_0_3>
                                        <Kaurilandingpage_0_0_0_0_0_0_0_0_4>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_0_4_0>
                                                <Kaurilandingpage_roadmap_1>
                                                    Roadmap
                                                </Kaurilandingpage_roadmap_1>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_0_4_0>
                                        </Kaurilandingpage_0_0_0_0_0_0_0_0_4>
                                        <Kaurilandingpage_0_0_0_0_0_0_0_0_5>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_0_5_0>
                                                <Kaurilandingpage_vision_paper_1>
                                                    Vision Paper
                                                </Kaurilandingpage_vision_paper_1>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_0_5_0>
                                        </Kaurilandingpage_0_0_0_0_0_0_0_0_5>
                                    </Kaurilandingpage_0_0_0_0_0_0_0_0>
                                    <Kaurilandingpage_0_0_0_0_0_0_0_1>
                                        <Kaurilandingpage_rectangle_2>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_1_0_0>
                                                <Kaurilandingpage_kauri_6>Kauri</Kaurilandingpage_kauri_6>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_1_0_0>
                                            <Kaurilandingpage_0_0_0_0_0_0_0_1_0_1>
                                                <Kaurilandingpage_technical_support_ne_1>
                                                    Technical Support Network for the Ethereum Ecosystem
                                                </Kaurilandingpage_technical_support_ne_1>
                                            </Kaurilandingpage_0_0_0_0_0_0_0_1_0_1>
                                        </Kaurilandingpage_rectangle_2>
                                    </Kaurilandingpage_0_0_0_0_0_0_0_1>
                                </Kaurilandingpage_bitmap_7>
                            </Kaurilandingpage_0_0_0_0_0_0>
                        </Kaurilandingpage_screen_size_group_3>
                        <Kaurilandingpage_path_1>
                            <Kaurilandingpage_0_0_0_0_1_0>
                                <Kaurilandingpage_open_support_for_ope_5>
                                    Open Support for Open Source
                                </Kaurilandingpage_open_support_for_ope_5>
                            </Kaurilandingpage_0_0_0_0_1_0>
                            <Kaurilandingpage_0_0_0_0_1_1>
                                <Kaurilandingpage_open_source_support_1>
                                    <div>Open source support is either expensive and dominated by centralized organizations, or nonexistent. </div>
                                    <div>{"This doesn't fit the spirit of open source, and is ineffective for individual developers and SMEs. "}</div>
                                    <div>{"At Kauri, we're building a decentralized technical support network to serve developers at all levels and organizations."}</div>
                                </Kaurilandingpage_open_source_support_1>
                            </Kaurilandingpage_0_0_0_0_1_1>
                        </Kaurilandingpage_path_1>
                    </Kaurilandingpage_0_0_0_0>
                </Kaurilandingpage_0_0_0>
            </Kaurilandingpage_0_0>
        </Kaurilandingpage_0>
        <Kaurilandingpage_1>
            <Kaurilandingpage_path_4>
                <Kaurilandingpage_1_0_0>
                    <Kaurilandingpage_1_0_0_0 /> 
                    <Kaurilandingpage_who_is_kauri_for__1>
                        {"Who is Kauri for?"}
                    </Kaurilandingpage_who_is_kauri_for__1>
                    <Kaurilandingpage_1_0_0_2 /> 
                </Kaurilandingpage_1_0_0>
                <Kaurilandingpage_1_0_1>
                    <Kaurilandingpage_1_0_1_0 /> 
                    <Kaurilandingpage_icons8 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1280773196123570-1522016388382-BA6090FD-354D-4D4C-B993-7DC8C8309E17.png" /> 
                    <Kaurilandingpage_1_0_1_2 /> 
                    <Kaurilandingpage_icons8_c src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5004830447293236-1522016388512-E78D13F8-F1D7-4DB0-9F6C-04759CC59BAD.png" /> 
                    <Kaurilandingpage_1_0_1_4 /> 
                    <Kaurilandingpage_icons8_m src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1184953189708700-1522016388513-D02F7603-8731-467C-A2EE-18C2EF73C1EB.png" /> 
                    <Kaurilandingpage_1_0_1_6 /> 
                </Kaurilandingpage_1_0_1>
                <Kaurilandingpage_1_0_2>
                    <Kaurilandingpage_1_0_2_0 /> 
                    <Kaurilandingpage_learn_get_help_1>
                        Learn / Get Help
                    </Kaurilandingpage_learn_get_help_1>
                    <Kaurilandingpage_1_0_2_2 /> 
                    <Kaurilandingpage_contribute_1>
                        Contribute
                    </Kaurilandingpage_contribute_1>
                    <Kaurilandingpage_1_0_2_4 /> 
                    <Kaurilandingpage_support_8>
                        Support
                    </Kaurilandingpage_support_8>
                    <Kaurilandingpage_1_0_2_6 /> 
                </Kaurilandingpage_1_0_2>
                <Kaurilandingpage_1_0_3>
                    <Kaurilandingpage_1_0_3_0>
                        <Kaurilandingpage_1_0_3_0_0>
                            <Kaurilandingpage_receive_any_level_of_1>
                                Receive any level of help, from self-service, frequently asked questions in the knowledge base, to hands-on technical support.
                            </Kaurilandingpage_receive_any_level_of_1>
                        </Kaurilandingpage_1_0_3_0_0>
                    </Kaurilandingpage_1_0_3_0>
                    <Kaurilandingpage_allow_kauri_s_best_p_1>
                        {"Allow Kauri's best providers to flourish on the platform by providing financial proof of their capabilities, earning a portion of their revenue as a reward."}
                    </Kaurilandingpage_allow_kauri_s_best_p_1>
                    <Kaurilandingpage_monetize_your_expert_1>
                        Monetize your expertise and knowledge by providing public and one-on-one support to individual developers, small teams, and large enterprises.
                    </Kaurilandingpage_monetize_your_expert_1>
                </Kaurilandingpage_1_0_3>
            </Kaurilandingpage_path_4>
        </Kaurilandingpage_1>
        <Kaurilandingpage_2>
            <Kaurilandingpage_path_9>
                <Kaurilandingpage_2_0_0>
                    <Kaurilandingpage_2_0_0_0 /> 
                    <Kaurilandingpage_kauri_features_copy_1>
                        Kauri Features
                    </Kaurilandingpage_kauri_features_copy_1>
                    <Kaurilandingpage_2_0_0_2 /> 
                </Kaurilandingpage_2_0_0>
                <Kaurilandingpage_2_0_1>
                    <Kaurilandingpage_2_0_1_0 /> 
                    <Kaurilandingpage_2_0_1_1>
                        <Kaurilandingpage_2_0_1_1_0 /> 
                        <Kaurilandingpage_2_0_1_1_1>
                            <Kaurilandingpage_icons8_l src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5153118949933321-1522016388385-1C37B732-ACB2-4DD6-9E36-A9E71123E0C3.png" /> 
                        </Kaurilandingpage_2_0_1_1_1>
                        <Kaurilandingpage_2_0_1_1_2>
                            <Kaurilandingpage_browse_1>
                                Browse
                            </Kaurilandingpage_browse_1>
                        </Kaurilandingpage_2_0_1_1_2>
                        <Kaurilandingpage_2_0_1_1_3>
                            <Kaurilandingpage_icons8_e src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1696194736658157-1522016388987-8BE85E5B-05EC-4DA1-B8D9-E661DFC10073.png" /> 
                        </Kaurilandingpage_2_0_1_1_3>
                    </Kaurilandingpage_2_0_1_1>
                    <Kaurilandingpage_2_0_1_2>
                        <Kaurilandingpage_2_0_1_2_0>
                            <Kaurilandingpage_group_3 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1460815267825802-1522016388447-08BC1E6E-10A7-4AE6-B9C6-8E33384C2981.png" /> 
                        </Kaurilandingpage_2_0_1_2_0>
                    </Kaurilandingpage_2_0_1_2>
                    <Kaurilandingpage_2_0_1_3>
                        <Kaurilandingpage_2_0_1_3_0>
                            <Kaurilandingpage_2_0_1_3_0_0>
                                <Kaurilandingpage_icons8_t src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1784151523073462-1522016388314-389AB543-CADC-4E3B-A721-E0F393A9D560.png" /> 
                                <Kaurilandingpage_fill_3 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6604751752327649-1522016388312-0183B1F4-4D98-4F7D-85DD-A927552E6133.png" /> 
                                <Kaurilandingpage_icons8_co src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6128470349929339-1522016388310-73BB467C-3DE9-4805-9274-B3519F4DD3E9.png" /> 
                            </Kaurilandingpage_2_0_1_3_0_0>
                        </Kaurilandingpage_2_0_1_3_0>
                    </Kaurilandingpage_2_0_1_3>
                    <Kaurilandingpage_2_0_1_4>
                        <Kaurilandingpage_2_0_1_4_0>
                            <Kaurilandingpage_group_4 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9005053387592517-1522016388450-FD84057F-659D-4299-A1C8-3221EBA4F30D.png" /> 
                        </Kaurilandingpage_2_0_1_4_0>
                    </Kaurilandingpage_2_0_1_4>
                    <Kaurilandingpage_2_0_1_5>
                        <Kaurilandingpage_2_0_1_5_0 /> 
                        <Kaurilandingpage_2_0_1_5_1>
                            <Kaurilandingpage_icons8_a src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4576114152103211-1522016388391-41274CB1-E790-4064-B057-CD54DB5F869A.png" /> 
                            <Kaurilandingpage_2_0_1_5_1_1 /> 
                        </Kaurilandingpage_2_0_1_5_1>
                        <Kaurilandingpage_2_0_1_5_2>
                            <Kaurilandingpage_request_1>
                                Request
                            </Kaurilandingpage_request_1>
                        </Kaurilandingpage_2_0_1_5_2>
                        <Kaurilandingpage_2_0_1_5_3>
                            <Kaurilandingpage_icons8_s src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1309837971697930-1522016388452-28F56DB8-05A5-497A-8EBC-9846A2659FF8.png" /> 
                            <Kaurilandingpage_2_0_1_5_3_1 /> 
                        </Kaurilandingpage_2_0_1_5_3>
                    </Kaurilandingpage_2_0_1_5>
                    <Kaurilandingpage_2_0_1_6 /> 
                </Kaurilandingpage_2_0_1>
                <Kaurilandingpage_2_0_2>
                    <Kaurilandingpage_2_0_2_0 /> 
                    <Kaurilandingpage_contribute_6>
                        Contribute 
                    </Kaurilandingpage_contribute_6>
                    <Kaurilandingpage_2_0_2_2 /> 
                    <Kaurilandingpage_support_2>
                        Support
                    </Kaurilandingpage_support_2>
                    <Kaurilandingpage_2_0_2_4 /> 
                </Kaurilandingpage_2_0_2>
            </Kaurilandingpage_path_9>
        </Kaurilandingpage_2>
        <Kaurilandingpage_3>
            <Kaurilandingpage_path_13>
                <Kaurilandingpage_3_0_0>
                    <Kaurilandingpage_3_0_0_0 /> 
                    <Kaurilandingpage_road_map_1>
                        Road map
                    </Kaurilandingpage_road_map_1>
                    <Kaurilandingpage_3_0_0_2 /> 
                </Kaurilandingpage_3_0_0>
                <Kaurilandingpage_3_0_1>
                    <Kaurilandingpage_3_0_1_0 /> 
                    <Kaurilandingpage_lorem_ipsum_dolor_si_4>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis luctus augue. Proin dignissim tellus at pharetra consectetur. 
                    </Kaurilandingpage_lorem_ipsum_dolor_si_4>
                    <Kaurilandingpage_3_0_1_2 /> 
                </Kaurilandingpage_3_0_1>
                <Kaurilandingpage_3_0_2 /> 
                <Kaurilandingpage_3_0_3>
                    <Kaurilandingpage_3_0_3_0 /> 
                    <Kaurilandingpage_phase_1>
                        Phase 1
                    </Kaurilandingpage_phase_1>
                    <Kaurilandingpage_3_0_3_2 /> 
                    <Kaurilandingpage_phase_2>
                        Phase 2
                    </Kaurilandingpage_phase_2>
                    <Kaurilandingpage_3_0_3_4 /> 
                    <Kaurilandingpage_phase_3>
                        Phase 3
                    </Kaurilandingpage_phase_3>
                    <Kaurilandingpage_3_0_3_6 /> 
                </Kaurilandingpage_3_0_3>
                <Kaurilandingpage_3_0_4>
                    <Kaurilandingpage_3_0_4_0 /> 
                    <Kaurilandingpage_line_7 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7821514930297160-1522016388990-3B09A1E4-03CE-4E2F-88E4-368EF7B00978.png" /> 
                    <Kaurilandingpage_3_0_4_2 /> 
                </Kaurilandingpage_3_0_4>
                <Kaurilandingpage_3_0_5 /> 
            </Kaurilandingpage_path_13>
        </Kaurilandingpage_3>
        <Kaurilandingpage_4>
            <Kaurilandingpage_rectangle_5>
                <Kaurilandingpage_4_0_0>
                    <Kaurilandingpage_4_0_0_0 /> 
                    <Kaurilandingpage_vision_paper_copy_7>
                        Vision Paper
                    </Kaurilandingpage_vision_paper_copy_7>
                    <Kaurilandingpage_4_0_0_2 /> 
                </Kaurilandingpage_4_0_0>
                <Kaurilandingpage_4_0_1>
                    <Kaurilandingpage_4_0_1_0 /> 
                    <Kaurilandingpage_lorem_ipsum_dolor_si_copy_1>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis luctus augue. Proin dignissim tellus at pharetra consectetur. 
                    </Kaurilandingpage_lorem_ipsum_dolor_si_copy_1>
                    <Kaurilandingpage_4_0_1_2 /> 
                </Kaurilandingpage_4_0_1>
                <Kaurilandingpage_4_0_2>
                    <Kaurilandingpage_4_0_2_0 /> 
                    <Kaurilandingpage_group_2 src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5732685578404367-1522016388510-BDC7E470-D5BA-422A-8FB0-B9F68962E645.png" /> 
                    <Kaurilandingpage_4_0_2_2 /> 
                </Kaurilandingpage_4_0_2>
                <Kaurilandingpage_4_0_3>
                    <Kaurilandingpage_4_0_3_0 /> 
                    <Kaurilandingpage_path_12>
                        <Kaurilandingpage_4_0_3_1_0>
                            <Kaurilandingpage_view_paper_copy_5>
                                View paper
                            </Kaurilandingpage_view_paper_copy_5>
                        </Kaurilandingpage_4_0_3_1_0>
                    </Kaurilandingpage_path_12>
                    <Kaurilandingpage_4_0_3_2 /> 
                </Kaurilandingpage_4_0_3>
            </Kaurilandingpage_rectangle_5>
        </Kaurilandingpage_4>
        <Kaurilandingpage_5>
            <Kaurilandingpage_path_3>
                <Kaurilandingpage_5_0_0>
                    <Kaurilandingpage_5_0_0_0 /> 
                    <Kaurilandingpage_subscribe_copy_4>
                        Subscribe
                    </Kaurilandingpage_subscribe_copy_4>
                    <Kaurilandingpage_5_0_0_2 /> 
                </Kaurilandingpage_5_0_0>
                <Kaurilandingpage_5_0_1>
                    <Kaurilandingpage_5_0_1_0 /> 
                    <Kaurilandingpage_path_43>
                        <Kaurilandingpage_5_0_1_1_0>
                            <Kaurilandingpage_email_address_1>
                                email address
                            </Kaurilandingpage_email_address_1>
                        </Kaurilandingpage_5_0_1_1_0>
                    </Kaurilandingpage_path_43>
                    <Kaurilandingpage_5_0_1_2 /> 
                </Kaurilandingpage_5_0_1>
                <Kaurilandingpage_5_0_2>
                    <Kaurilandingpage_5_0_2_0 /> 
                    <Kaurilandingpage_path_10>
                        <Kaurilandingpage_5_0_2_1_0>
                            <Kaurilandingpage_sign_up_1>
                                Sign Up
                            </Kaurilandingpage_sign_up_1>
                        </Kaurilandingpage_5_0_2_1_0>
                    </Kaurilandingpage_path_10>
                    <Kaurilandingpage_5_0_2_2 /> 
                </Kaurilandingpage_5_0_2>
            </Kaurilandingpage_path_3>
        </Kaurilandingpage_5>
    </Kaurilandingpage_kaurilandingpage_1>;
};

export default function(props) {
    return render.apply({props: props});
}
