// Generated by https://pagedraw.io/pages/11218
import React from 'react';
import './profile.css';


function render() {
    return <div className="profile-profile-4">
        <div className="profile-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7100773407651961-1531049878267-16A62E74-D71B-4252-96C3-33DF76C3E4C0.png" className="profile-bitmap-7" /> 
            <div className="profile-0-1">
                <div className="profile-0-1-0">
                    <div className="profile-npka2">npka212</div>
                </div>
            </div>
            <div className="profile-0-2">
                <div className="profile-0-2-0">
                    <div className="profile-oval-1">
                        <div className="profile-0-2-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9455024881162197-1531049878270-5F784032-B24E-47EF-95DA-2194CADA99BE.png" className="profile-icons8" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="profile-1">
            <div className="profile-oval_copy_9">
                <div className="profile-1-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9312076010025666-1531049878273-DC71E2E7-9B90-4BF0-AC92-CEBAA9A7ED39.png" className="profile-group_copy_5" /> 
                </div>
            </div>
            <div className="profile-1-1">
                <div className="profile-1-1-0">
                    <div className="profile-makerdao-1">MakerDao</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
