// Generated by https://pagedraw.io/pages/11218
import React from 'react';
import './projects.css';


function render() {
    return <div className="projects-projects-2">
        <div className="projects-0">
            <div className="projects-path-7">
                <div className="projects-0-0-0">
                    <div className="projects-community_copy_4">community</div>
                </div>
                <div className="projects-0-0-1">
                    <div className="projects-community_name-2">
                        Community Name
                    </div>
                </div>
                <div className="projects-0-0-2">
                    <div className="projects-two_line_description_copy_2">
                        <div>Two line description</div>
                        <div>Two line description</div>
                    </div>
                </div>
                <div className="projects-0-0-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1400870717296253-1531049878504-56D7BB46-5192-4187-8EE5-02DD57FAE0A6.png" className="projects-line_4" /> 
                </div>
                <div className="projects-0-0-4">
                    <div className="projects-0_">0</div>
                    <div className="projects-0_c">0</div>
                    <div className="projects-0_co">0</div>
                </div>
                <div className="projects-0-0-5">
                    <div className="projects-followers_copy_3">followers</div>
                    <div className="projects-articles_copy_1">articles</div>
                    <div className="projects-views_copy_2">views</div>
                </div>
            </div>
            <div className="projects-path-2">
                <div className="projects-0-1-0">
                    <div className="projects-community_copy-1">community</div>
                </div>
                <div className="projects-0-1-1">
                    <div className="projects-path-1" /> 
                </div>
                <div className="projects-0-1-2">
                    <div className="projects-community_name-1">
                        Community Name
                    </div>
                </div>
                <div className="projects-0-1-3">
                    <div className="projects-two_line_description_copy-1">
                        <div>Two line description</div>
                        <div>Two line description</div>
                    </div>
                </div>
                <div className="projects-0-1-4">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1835000681788316-1531049878502-97D58459-0437-4696-B73D-BAE5405A2E5E.png" className="projects-line_4_" /> 
                </div>
                <div className="projects-0-1-5">
                    <div className="projects-0_cop">0</div>
                    <div className="projects-0_copy">0</div>
                    <div className="projects-0_copy_">0</div>
                </div>
                <div className="projects-0-1-6">
                    <div className="projects-followers_copy-1">followers</div>
                    <div className="projects-articles_copy_15">articles</div>
                    <div className="projects-views_copy-1">views</div>
                </div>
            </div>
            <div className="projects-0-2">
                <div className="projects-0-2-0">
                    <div className="projects-path-16">
                        <div className="projects-0-2-0-0-0">
                            <div className="projects-community_copy_2">community</div>
                        </div>
                        <div className="projects-0-2-0-0-1">
                            <div className="projects-path-15" /> 
                        </div>
                        <div className="projects-0-2-0-0-2">
                            <div className="projects-community_name_copy-1">
                                Community Name
                            </div>
                        </div>
                        <div className="projects-0-2-0-0-3">
                            <div className="projects-two_line_description_copy_3">
                                <div>Two line description</div>
                                <div>Two line description</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="projects-0-2-1">
                    <div className="projects-path-17">
                        <div className="projects-0-2-1-0-0">
                            <div className="projects-0_copy_2">0</div>
                            <div className="projects-0_copy_20">0</div>
                            <div className="projects-0_copy_1">0</div>
                        </div>
                        <div className="projects-0-2-1-0-1">
                            <div className="projects-followers_copy_2">followers</div>
                            <div className="projects-articles_copy_18">articles</div>
                            <div className="projects-views_copy_3">views</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="projects-1">
            <div className="projects-path-150">
                <div className="projects-1-0-0">
                    <div className="projects-community_copy_3">community</div>
                </div>
                <div className="projects-1-0-1">
                    <div className="projects-community_name-9">
                        Community Name
                    </div>
                </div>
                <div className="projects-1-0-2">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1580617706422957-1531049878501-D1E477C9-14A8-40DC-9AFD-6ED0DD560995.png" className="projects-line_4_c" /> 
                </div>
                <div className="projects-1-0-3">
                    <div className="projects-0_copy_14">0</div>
                    <div className="projects-0_copy_12">0</div>
                    <div className="projects-0_copy_10">0</div>
                </div>
                <div className="projects-1-0-4">
                    <div className="projects-followers-1">followers</div>
                    <div className="projects-articles_copy_14">articles</div>
                    <div className="projects-views-3">views</div>
                </div>
            </div>
            <div className="projects-1-1">
                <div className="projects-1-1-0">
                    <div className="projects-path-6">
                        <div className="projects-1-1-0-0-0">
                            <div className="projects-community-1">community</div>
                        </div>
                        <div className="projects-1-1-0-0-1">
                            <div className="projects-community_name-95">
                                Community Name
                            </div>
                        </div>
                    </div>
                </div>
                <div className="projects-1-1-1">
                    <div className="projects-path-8">
                        <div className="projects-1-1-1-0-0">
                            <div className="projects-0_copy_18">0</div>
                            <div className="projects-0_copy_17">0</div>
                            <div className="projects-0_copy_16">0</div>
                        </div>
                        <div className="projects-1-1-1-0-1">
                            <div className="projects-followers-7">followers</div>
                            <div className="projects-articles_copy_16">articles</div>
                            <div className="projects-views-9">views</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
