// Generated by https://pagedraw.io/pages/11218
import React from 'react';
import './requests.css';


function render() {
    return <div className="requests-requests-1">
        <div className="requests-0">
            <div className="requests-path-2">
                <div className="requests-0-0-0">
                    <div className="requests-path-6">
                        <div className="requests-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5652287069790071-1531049878264-B5B8C02C-682D-4784-9B7C-9427D8341133.png" className="requests-oval_copy_1" /> 
                        </div>
                        <div className="requests-0-0-0-0-1">
                            <div className="requests-username_copy_2">username</div>
                        </div>
                    </div>
                    <div className="requests-0-0-0-1">
                        <div className="requests-0-0-0-1-0">
                            <div className="requests-request_copy_3">request</div>
                        </div>
                        <div className="requests-0-0-0-1-1">
                            <div className="requests-robust_alerting_tuto_copy-8">
                                Robust alerting tutorial for Collateral Debt Position owners
                            </div>
                        </div>
                        <div className="requests-0-0-0-1-2">
                            <div className="requests-deadline_2">
                                {"DEADLINE  2 months (24 JUN 2017)"}
                            </div>
                            <div className="requests-tags_makerdao_bloc_copy-1">
                                {"tags  Makerdao • Blockchain • Ethereum • +3"}
                            </div>
                        </div>
                    </div>
                    <div className="requests-0-0-0-2">
                        <div className="requests-0-0-0-2-0">
                            <div className="requests-0-1">0</div>
                        </div>
                        <div className="requests-0-0-0-2-1">
                            <div className="requests-in_progress-5">IN PROGRESS</div>
                        </div>
                    </div>
                    <div className="requests-0-0-0-3">
                        <div className="requests-0-0-0-3-0">
                            <div className="requests-1-3">1</div>
                        </div>
                        <div className="requests-0-0-0-3-1">
                            <div className="requests-comments-2">COMMENTS</div>
                        </div>
                    </div>
                    <div className="requests-0-0-0-4">
                        <div className="requests-0-0-0-4-0">
                            <div className="requests-0_">0.01 ETH</div>
                        </div>
                        <div className="requests-0-0-0-4-1">
                            <div className="requests-_2">$20.00</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="requests-1">
            <div className="requests-path-22">
                <div className="requests-1-0-0">
                    <div className="requests-request-5">request</div>
                </div>
                <div className="requests-1-0-1">
                    <div className="requests-1-0-1-0">
                        <div className="requests-1-0-1-0-0">
                            <div className="requests-1-0-1-0-0-0">
                                <div className="requests-robust_alerting_tuto-4">
                                    Robust alerting tutorial for Collateral Debt Position owners
                                </div>
                                <div className="requests-this_bounty_is_a_par-1">
                                    {"This bounty is a part of the Kauri technical content competition: https://beta.bounties.network/bounty/v1/355"}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="requests-1-0-2">
                    <div className="requests-deadline_2_">
                        {"DEADLINE 2 months (24 JUN 2017)"}
                    </div>
                </div>
                <div className="requests-1-0-3">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2829452371038746-1531049878265-2CCE7C1C-E1EC-49B1-A50E-05522F8ED876.png" className="requests-line_4" /> 
                </div>
                <div className="requests-1-0-4">
                    <div className="requests-0_0">0.01 ETH</div>
                </div>
                <div className="requests-1-0-5">
                    <div className="requests-_20">$20.00</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
