// Generated by https://pagedraw.io/pages/9527
import React from 'react';
import './toggles.css';


function render() {
    return <div className="toggles-toggles-00">
        <div className="toggles-0">
            <div className="toggles-0-0">
                <div className="toggles-0-0-0">
                    <div className="toggles-0-0-0-0">
                        <div className="toggles-t_-_a_-_g-0">
                            <div className="toggles-0-0-0-0-0-0">
                                <div className="toggles-rectangle-0">
                                    <div className="toggles-0-0-0-0-0-0-0-0">
                                        <div className="toggles-vector-0" /> 
                                        <div className="toggles-0-0-0-0-0-0-0-0-1">
                                            <div className="toggles-0-0-0-0-0-0-0-0-1-0">
                                                <div className="toggles-vector-00" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="toggles-0-0-0-0-0-1">
                                <div className="toggles-toggles-0">Toggles</div>
                            </div>
                        </div>
                        <div className="toggles-hope_this_can_help_you_in_some_way_if_you_have_any_feedback_on_this_system_feel_free_to_e-mail_me_-_juauzaraujo_gmail_com_juauz_com-0">
                            <div>Hope this can help you in some way.</div>
                            <br/>
                            <div>If you have any feedback on this system, feel free to e-mail me - juauzaraujo@gmail.com</div>
                            <br/>
                            <div>juauz.com</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-0-1">
                <div className="toggles-0-1-0">
                    <div className="toggles-quarks-0">Quarks</div>
                </div>
                <div className="toggles-0-1-1">
                    <div className="toggles-0-1-1-0">
                        <div className="toggles-0-1-1-0-0">
                            <div className="toggles-0-1-1-0-0-0">
                                <div className="toggles-active_bg-0">Active bg</div>
                                <div className="toggles-t_-_i_-_t_-_l_-_e-0" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="toggles-0-1-2">
                    <div className="toggles-active_bg-00">
                        <div className="toggles-0-1-2-0-0">
                            <div className="toggles-rectangle_9" /> 
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-0-2">
                <div className="toggles-0-2-0">
                    <div className="toggles-0-2-0-0">
                        <div className="toggles-0-2-0-0-0">
                            <div className="toggles-0-2-0-0-0-0">
                                <div className="toggles-inactive_bg-0">Inactive bg</div>
                                <div className="toggles-t_-_i_-_t_-_l_-_e-00" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="toggles-0-2-1">
                    <div className="toggles-inactive_bg-00">
                        <div className="toggles-0-2-1-0-0">
                            <div className="toggles-rectangle_9-0" /> 
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-0-3">
                <div className="toggles-0-3-0">
                    <div className="toggles-0-3-0-0">
                        <div className="toggles-0-3-0-0-0">
                            <div className="toggles-0-3-0-0-0-0">
                                <div className="toggles-gold_bg-0">Gold bg</div>
                                <div className="toggles-t_-_i_-_t_-_l_-_e-000" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="toggles-0-3-1">
                    <div className="toggles-gold_bg-00">
                        <div className="toggles-0-3-1-0-0">
                            <div className="toggles-rectangle_9-00" /> 
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-0-4">
                <div className="toggles-0-4-0">
                    <div className="toggles-t_-_i_-_t_-_l_-_e-0000">
                        <div className="toggles-0-4-0-0-0">
                            <div className="toggles-white_circle-0">White Circle</div>
                        </div>
                    </div>
                </div>
                <div className="toggles-0-4-1">
                    <div className="toggles-white_circle-00">
                        <div className="toggles-0-4-1-0-0">
                            <div className="toggles-ellipse-0" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="toggles-1">
            <div className="toggles-atoms-0">Atoms</div>
        </div>
        <div className="toggles-2">
            <div className="toggles-2-0">
                <div className="toggles-2-0-0">
                    <div className="toggles-2-0-0-0">
                        <div className="toggles-active_toggle-0">
                            Active Toggle
                        </div>
                        <div className="toggles-t_-_i_-_t_-_l_-_e-00000" /> 
                    </div>
                </div>
            </div>
            <div className="toggles-t_-_i_-_t_-_l_-_e-000002">
                <div className="toggles-2-1-0">
                    <div className="toggles-inactive_toggle-0">
                        Inactive Toggle
                    </div>
                </div>
            </div>
            <div className="toggles-2-2">
                <div className="toggles-2-2-0">
                    <div className="toggles-2-2-0-0">
                        <div className="toggles-gold_toggle-0">Gold Toggle</div>
                        <div className="toggles-t_-_i_-_t_-_l_-_e-000000" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="toggles-3">
            <div className="toggles-active_toggle_-0">
                <div className="toggles-3-0-0">
                    <div className="toggles-3-0-0-0">
                        <div className="toggles-b-1">
                            Source component not found
                        </div>
                        <div className="toggles-b-4">
                            Source component not found
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-inactive_toggle_-0">
                <div className="toggles-3-1-0">
                    <div className="toggles-3-1-0-0">
                        <div className="toggles-b-2">
                            Source component not found
                        </div>
                        <div className="toggles-b-9">
                            Source component not found
                        </div>
                    </div>
                </div>
            </div>
            <div className="toggles-gold_toggle_-0">
                <div className="toggles-3-2-0">
                    <div className="toggles-3-2-0-0">
                        <div className="toggles-b-8">
                            Source component not found
                        </div>
                        <div className="toggles-b-13">
                            Source component not found
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="toggles-4">
            <div className="toggles-molecules-00">
                <div className="toggles-4-0-0">
                    <div className="toggles-molecules-0">
                        <div className="toggles-4-0-0-0-0">
                            <div className="toggles-dynamic_elements-0">
                                Dynamic Elements
                            </div>
                        </div>
                        <div className="toggles-4-0-0-0-1">
                            <div className="toggles-these_elements_combine_components_that_can_be_hidden_to_show_different_status_of_each_component_use_ctrl_shift_h_to_hide_multiple_selected_components_at_the_same_time_-0">
                                <div>These elements combine Components that can be hidden to show different status of each Component.</div>
                                <br/>
                                <div>Use Ctrl+Shift+H to hide multiple selected Components at the same time.</div>
                            </div>
                            <div className="toggles-4-0-0-0-1-1">
                                <div className="toggles-4-0-0-0-1-1-0">
                                    <div className="toggles-4-0-0-0-1-1-0-0">
                                        <div className="toggles-4-0-0-0-1-1-0-0-0">
                                            <div className="toggles-4-0-0-0-1-1-0-0-0-0">
                                                <div className="toggles-_toggles-0">
                                                    {"🦄🦄🦄 Toggles"}
                                                </div>
                                                <div className="toggles-t_-_i_-_t_-_l_-_e-0000028" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="toggles-4-0-0-0-1-1-1">
                                    <div className="toggles-_toggles-00">
                                        <div className="toggles-4-0-0-0-1-1-1-0-0">
                                            <div className="toggles-4-0-0-0-1-1-1-0-0-0">
                                                <div className="toggles-b-93">
                                                    Source component not found
                                                </div>
                                                <div className="toggles-b-6">
                                                    Source component not found
                                                </div>
                                                <div className="toggles-b-5">
                                                    Source component not found
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
